from django.urls import path

from . import views

app_name = "academico"

urlpatterns = [
    path("cursos/", views.CursoListView.as_view(), name="curso_list"),
    path("cursos/nuevo/", views.CursoCreateView.as_view(), name="curso_nuevo"),
    path("cursos/<int:pk>/editar/", views.CursoUpdateView.as_view(), name="curso_editar"),
    path("cursos/<int:pk>/toggle-activo/", views.CursoToggleActivoView.as_view(), name="curso_toggle_activo"),
    path("aulas/", views.AulaListView.as_view(), name="aula_list"),
    path("aulas/nueva/", views.AulaCreateView.as_view(), name="aula_nueva"),
    path("aulas/<int:pk>/editar/", views.AulaUpdateView.as_view(), name="aula_editar"),
    path("materias/", views.MateriaListView.as_view(), name="materia_list"),
    path("materias/nueva/", views.MateriaCreateView.as_view(), name="materia_nueva"),
    path("materias/<int:pk>/editar/", views.MateriaUpdateView.as_view(), name="materia_editar"),
    path("periodos/", views.PeriodoListView.as_view(), name="periodo_list"),
    path("periodos/nuevo/", views.PeriodoCreateView.as_view(), name="periodo_nuevo"),
    path("periodos/<int:pk>/editar/", views.PeriodoUpdateView.as_view(), name="periodo_editar"),
    path("horario-distribucion/", views.HorarioDistribucionListView.as_view(), name="horario_distribucion"),
    path("horario-distribucion/nuevo/", views.HorarioDistribucionCreateView.as_view(), name="horario_distribucion_nuevo"),
    path("horario-distribucion/<int:curso_pk>/editar/", views.HorarioDistribucionUpdateView.as_view(), name="horario_distribucion_editar"),
    path("planificacion-academica/", views.PlanificacionAcademicaView.as_view(), name="planificacion_academica"),
    path("asignaturas/", views.AsignaturaListView.as_view(), name="asignatura_list"),
    path("asignaturas/nueva/", views.AsignaturaCreateView.as_view(), name="asignatura_nueva"),
    path("asignaturas/<int:pk>/editar/", views.AsignaturaUpdateView.as_view(), name="asignatura_editar"),
    path("temarios/", views.TemarioListView.as_view(), name="temario_list"),
    path("temarios/nuevo/", views.TemarioCreateView.as_view(), name="temario_nuevo"),
    path("temarios/<int:pk>/editar/", views.TemarioUpdateView.as_view(), name="temario_editar"),
    path("horarios/", views.HorarioClaseListView.as_view(), name="horario_list"),
    path("horarios/calendario/", views.HorarioCalendarioView.as_view(), name="horario_calendario"),
    path("horarios/asignar/", views.HorarioAsignacionView.as_view(), name="horario_asignacion"),
    path("horarios/nuevo/", views.HorarioClaseCreateView.as_view(), name="horario_nuevo"),
    path("horarios/<int:pk>/editar/", views.HorarioClaseUpdateView.as_view(), name="horario_editar"),
    path("temas/", views.TemaListView.as_view(), name="tema_list"),
    path("temas/nuevo/", views.TemaCreateView.as_view(), name="tema_nuevo"),
    path("temas/<int:pk>/editar/", views.TemaUpdateView.as_view(), name="tema_editar"),
    path("planificaciones/", views.PlanificacionClaseListView.as_view(), name="planificacion_list"),
    path("planificaciones/nueva/", views.PlanificacionClaseCreateView.as_view(), name="planificacion_nueva"),
    path("planificaciones/<int:pk>/editar/", views.PlanificacionClaseUpdateView.as_view(), name="planificacion_editar"),
    path("bancos-preguntas/", views.BancoPreguntaListView.as_view(), name="banco_list"),
    path("bancos-preguntas/nuevo/", views.BancoPreguntaCreateView.as_view(), name="banco_nuevo"),
    path("bancos-preguntas/<int:pk>/editar/", views.BancoPreguntaUpdateView.as_view(), name="banco_editar"),
    path("preguntas/", views.PreguntaListView.as_view(), name="pregunta_list"),
    path("preguntas/nueva/", views.PreguntaCreateView.as_view(), name="pregunta_nueva"),
    path("preguntas/<int:pk>/editar/", views.PreguntaUpdateView.as_view(), name="pregunta_editar"),
]
