# Generated by Django 5.2.17 on 2026-08-20 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('legal_name', models.CharField(blank=True, max_length=220)),
                ('tax_id', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('closed', 'Cerrado')], db_index=True, default='draft', max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_periods', to='institutions.institution')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('section', models.CharField(blank=True, max_length=40)),
                ('shift', models.CharField(blank=True, choices=[('morning', 'Matutina'), ('afternoon', 'Vespertina'), ('night', 'Nocturna'), ('weekend', 'Fin de semana')], max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='institutions.academicperiod')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='institutions.institution')),
            ],
            options={
                'ordering': ['academic_period', 'name', 'section'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('institution', 'academic_period', 'name', 'section'), name='uniq_active_classroom_by_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('institution', 'name'), name='uniq_active_period_by_institution_name'),
        ),
    ]
