# Generated by Django 5.2.17 on 2026-08-20 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('enrollment_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('suspended', 'Suspendida'), ('withdrawn', 'Retirada'), ('completed', 'Completada')], db_index=True, default='pending', max_length=20)),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='enrollments/signed/')),
                ('notes', models.TextField(blank=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='institutions.academicperiod')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='institutions.classroom')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='institutions.institution')),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_changes', to=settings.AUTH_USER_MODEL)),
                ('from_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_moves_from', to='institutions.classroom')),
                ('to_classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_moves_to', to='institutions.classroom')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_history', to='people.enrollment')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(default='cedula', max_length=20)),
                ('document_number', models.CharField(max_length=30)),
                ('first_names', models.CharField(max_length=120)),
                ('last_names', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('secondary_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representatives', to='institutions.institution')),
            ],
            options={
                'ordering': ['last_names', 'first_names'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(default='cedula', max_length=20)),
                ('document_number', models.CharField(max_length=30)),
                ('first_names', models.CharField(max_length=120)),
                ('last_names', models.CharField(max_length=120)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('withdrawn', 'Retirado'), ('graduated', 'Graduado')], db_index=True, default='active', max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='institutions.institution')),
            ],
            options={
                'ordering': ['last_names', 'first_names'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='people.student'),
        ),
        migrations.CreateModel(
            name='StudentRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(max_length=60)),
                ('is_primary', models.BooleanField(default=False)),
                ('emergency_contact', models.BooleanField(default=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_representatives', to='people.representative')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_representatives', to='people.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='representative',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('institution', 'document_number'), name='uniq_active_representative_document_by_institution'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('institution', 'document_number'), name='uniq_active_student_document_by_institution'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'academic_period'), name='uniq_active_enrollment_by_student_period'),
        ),
        migrations.AddConstraint(
            model_name='studentrepresentative',
            constraint=models.UniqueConstraint(fields=('student', 'representative'), name='uniq_student_representative'),
        ),
    ]
