--
-- PostgreSQL database dump
--

\restrict sdluDT2VsFNCuBsc1y0Q0dxCm4wWhxXG8vCgSRZtcVhEfaQuJs2GI0Q3mHP9rKY

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg12+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg12+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: academico; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA academico;


--
-- Name: auditoria; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA auditoria;


--
-- Name: cartera; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA cartera;


--
-- Name: core; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA core;


--
-- Name: matricula; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA matricula;


--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


--
-- Name: hstore; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;


--
-- Name: EXTENSION hstore; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION hstore IS 'data type for storing sets of (key, value) pairs';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asignatura; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.asignatura (
    id integer NOT NULL,
    codigo character varying(40) NOT NULL,
    nombre character varying(160) NOT NULL,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_empresa integer NOT NULL,
    id_usuario_updated integer
);


--
-- Name: asignatura_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.asignatura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.asignatura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: asistencia; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.asistencia (
    id integer NOT NULL,
    estado character varying(20) NOT NULL,
    observacion text,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_estudiante integer NOT NULL,
    id_registrado_por integer,
    id_usuario_updated integer,
    id_planificacion_clase integer NOT NULL
);


--
-- Name: asistencia_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.asistencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.asistencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: banco_pregunta; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.banco_pregunta (
    id integer NOT NULL,
    tipo character varying(20) NOT NULL,
    meta_preguntas integer NOT NULL,
    revisado_coordinacion boolean NOT NULL,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_asignatura integer NOT NULL,
    id_empresa integer NOT NULL,
    id_usuario_updated integer,
    id_subtema integer,
    id_tema integer
);


--
-- Name: banco_pregunta_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.banco_pregunta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.banco_pregunta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: docente_asignatura; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.docente_asignatura (
    id integer NOT NULL,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_asignatura integer NOT NULL,
    id_aula integer,
    id_docente integer NOT NULL,
    id_empresa integer NOT NULL,
    id_periodo_academico integer NOT NULL,
    id_usuario_updated integer
);


--
-- Name: docente_asignatura_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.docente_asignatura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.docente_asignatura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluacion; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.evaluacion (
    id integer NOT NULL,
    titulo character varying(180) NOT NULL,
    tipo character varying(20) NOT NULL,
    fecha date NOT NULL,
    puntaje_maximo numeric(5,2) NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_asignatura integer NOT NULL,
    id_creado_por integer,
    id_empresa integer NOT NULL,
    id_usuario_updated integer,
    id_planificacion_clase integer,
    id_tema integer
);


--
-- Name: evaluacion_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.evaluacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.evaluacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluacion_resultado; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.evaluacion_resultado (
    id integer NOT NULL,
    nota numeric(5,2) NOT NULL,
    observacion text,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_estudiante integer NOT NULL,
    id_evaluacion integer NOT NULL,
    id_usuario_updated integer
);


--
-- Name: evaluacion_resultado_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.evaluacion_resultado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.evaluacion_resultado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: planificacion_clase; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.planificacion_clase (
    id integer NOT NULL,
    numero_clase integer NOT NULL,
    fecha_planificada date NOT NULL,
    objetivo text NOT NULL,
    actividades text NOT NULL,
    recursos_previstos text,
    estado character varying(20) NOT NULL,
    fecha_revision timestamp with time zone,
    notas_revision text,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_asignatura integer NOT NULL,
    id_aula integer NOT NULL,
    id_docente integer NOT NULL,
    id_empresa integer NOT NULL,
    id_revisado_por integer,
    id_usuario_updated integer,
    id_subtema integer,
    id_tema integer NOT NULL
);


--
-- Name: planificacion_clase_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.planificacion_clase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.planificacion_clase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pregunta; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.pregunta (
    id integer NOT NULL,
    enunciado text NOT NULL,
    respuestas jsonb NOT NULL,
    respuesta_correcta text,
    explicacion text,
    dificultad character varying(20) NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_revision timestamp with time zone,
    notas_revision text,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_banco_pregunta integer NOT NULL,
    id_creado_por integer NOT NULL,
    id_revisado_por integer,
    id_usuario_updated integer
);


--
-- Name: pregunta_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.pregunta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.pregunta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recurso_clase; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.recurso_clase (
    id integer NOT NULL,
    titulo character varying(180) NOT NULL,
    tipo character varying(20) NOT NULL,
    url text,
    archivo character varying(100),
    listo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_creado_por integer,
    id_planificacion_clase integer NOT NULL,
    id_usuario_updated integer
);


--
-- Name: recurso_clase_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.recurso_clase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.recurso_clase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subtema; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.subtema (
    id integer NOT NULL,
    nombre character varying(180) NOT NULL,
    orden integer NOT NULL,
    objetivo text,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_usuario_updated integer,
    id_tema integer NOT NULL
);


--
-- Name: subtema_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.subtema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.subtema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tema; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.tema (
    id integer NOT NULL,
    nombre character varying(180) NOT NULL,
    orden integer NOT NULL,
    objetivo text,
    numero_clases integer NOT NULL,
    dificultad character varying(20) NOT NULL,
    meta_preguntas_proceso integer NOT NULL,
    meta_preguntas_final integer NOT NULL,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_usuario_updated integer,
    id_temario integer NOT NULL
);


--
-- Name: tema_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.tema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.tema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: temario; Type: TABLE; Schema: academico; Owner: -
--

CREATE TABLE academico.temario (
    id integer NOT NULL,
    nombre character varying(180) NOT NULL,
    estado character varying(20) NOT NULL,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_asignatura integer NOT NULL,
    id_empresa integer NOT NULL,
    id_periodo_academico integer,
    id_usuario_updated integer
);


--
-- Name: temario_id_seq; Type: SEQUENCE; Schema: academico; Owner: -
--

ALTER TABLE academico.temario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME academico.temario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner; Type: TABLE; Schema: core; Owner: -
--

CREATE TABLE core.partner (
    id integer NOT NULL,
    codigo character varying(50),
    codigo_aux character varying(20),
    nombre text NOT NULL,
    identificacion character varying(20) NOT NULL,
    direccion character varying(200),
    telefono character varying(50),
    telefono_celular character varying(50),
    email text,
    fecha_nacimiento date,
    genero character varying(1),
    tipo character varying(2),
    ocupacion character varying(100),
    comentario text,
    es_cliente boolean NOT NULL,
    es_estudiante boolean NOT NULL,
    es_representante boolean NOT NULL,
    es_docente boolean NOT NULL,
    ingresar_portal boolean NOT NULL,
    activo boolean NOT NULL,
    tags public.hstore,
    creado timestamp with time zone NOT NULL,
    actualizado timestamp with time zone NOT NULL,
    id_empresa integer,
    id_operador_movil integer,
    id_usuario_updated integer,
    id_tipo_identificacion integer NOT NULL
);


--
-- Name: v_indicador_preguntas_docente; Type: VIEW; Schema: academico; Owner: -
--

CREATE VIEW academico.v_indicador_preguntas_docente AS
 SELECT bp.id_empresa,
    p.id_creado_por AS id_docente,
    docente.nombre AS docente,
    a.nombre AS asignatura,
    t.nombre AS tema,
    bp.tipo,
    bp.meta_preguntas,
    count(p.id) AS preguntas_creadas,
    (bp.meta_preguntas - count(p.id)) AS preguntas_pendientes
   FROM ((((academico.banco_pregunta bp
     JOIN academico.asignatura a ON ((a.id = bp.id_asignatura)))
     LEFT JOIN academico.tema t ON ((t.id = bp.id_tema)))
     LEFT JOIN academico.pregunta p ON (((p.id_banco_pregunta = bp.id) AND (p.activo = true))))
     LEFT JOIN core.partner docente ON ((docente.id = p.id_creado_por)))
  WHERE (bp.activo = true)
  GROUP BY bp.id_empresa, p.id_creado_por, docente.nombre, a.nombre, t.nombre, bp.tipo, bp.meta_preguntas;


--
-- Name: log_accion; Type: TABLE; Schema: auditoria; Owner: -
--

CREATE TABLE auditoria.log_accion (
    id integer NOT NULL,
    accion character varying(20) NOT NULL,
    modelo character varying(120) NOT NULL,
    object_id character varying(80),
    object_repr character varying(255),
    cambios jsonb NOT NULL,
    ip_address inet,
    user_agent text,
    created timestamp with time zone NOT NULL,
    id_empresa integer,
    id_usuario integer
);


--
-- Name: log_accion_id_seq; Type: SEQUENCE; Schema: auditoria; Owner: -
--

ALTER TABLE auditoria.log_accion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auditoria.log_accion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cuota; Type: TABLE; Schema: cartera; Owner: -
--

CREATE TABLE cartera.cuota (
    id integer NOT NULL,
    numero integer NOT NULL,
    fecha_pago_debito date NOT NULL,
    valor numeric(12,2) NOT NULL,
    valor_pagado numeric(12,2) NOT NULL,
    numero_recibo_factura_deposito character varying(60),
    observacion text,
    estado character varying(20) NOT NULL,
    prioridad character varying(20) NOT NULL,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_usuario_updated integer,
    id_plan_pago integer NOT NULL
);


--
-- Name: cuota_id_seq; Type: SEQUENCE; Schema: cartera; Owner: -
--

ALTER TABLE cartera.cuota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartera.cuota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forma_pago; Type: TABLE; Schema: cartera; Owner: -
--

CREATE TABLE cartera.forma_pago (
    id integer NOT NULL,
    nombre character varying(30) NOT NULL,
    tipo character varying(20),
    activo boolean NOT NULL,
    orden integer,
    es_venta boolean NOT NULL,
    es_pago boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_empresa integer NOT NULL,
    id_usuario_updated integer
);


--
-- Name: forma_pago_id_seq; Type: SEQUENCE; Schema: cartera; Owner: -
--

ALTER TABLE cartera.forma_pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartera.forma_pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pago; Type: TABLE; Schema: cartera; Owner: -
--

CREATE TABLE cartera.pago (
    id integer NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    valor numeric(12,2) NOT NULL,
    numero_documento character varying(60),
    comprobante character varying(100),
    comentario text,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_cuota integer NOT NULL,
    id_empresa integer NOT NULL,
    id_forma_pago integer NOT NULL,
    id_usuario integer,
    id_usuario_updated integer
);


--
-- Name: pago_id_seq; Type: SEQUENCE; Schema: cartera; Owner: -
--

ALTER TABLE cartera.pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartera.pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_pago; Type: TABLE; Schema: cartera; Owner: -
--

CREATE TABLE cartera.plan_pago (
    id integer NOT NULL,
    valor_total numeric(12,2) NOT NULL,
    valor_matricula numeric(12,2) NOT NULL,
    descuento numeric(12,2) NOT NULL,
    abono numeric(12,2) NOT NULL,
    saldo numeric(12,2) NOT NULL,
    estado character varying(20) NOT NULL,
    observacion text,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_empresa integer NOT NULL,
    id_ficha_inscripcion integer NOT NULL,
    id_usuario_updated integer
);


--
-- Name: plan_pago_id_seq; Type: SEQUENCE; Schema: cartera; Owner: -
--

ALTER TABLE cartera.plan_pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartera.plan_pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ficha_inscripcion; Type: TABLE; Schema: matricula; Owner: -
--

CREATE TABLE matricula.ficha_inscripcion (
    id integer NOT NULL,
    numero character varying(30) NOT NULL,
    fecha date NOT NULL,
    edad integer,
    colegio character varying(200),
    curso_grado character varying(120),
    nota_grado character varying(60),
    carrera character varying(160),
    universidad character varying(160),
    nombre_conyuge character varying(200),
    ocupacion_conyuge character varying(120),
    correo_estudiante text,
    correo_representante text,
    horario character varying(120),
    hora character varying(80),
    duracion character varying(80),
    forma_pago_convenio character varying(20),
    fecha_proximo_pago date,
    valor_proximo_pago numeric(12,2) NOT NULL,
    valor_total_curso numeric(12,2) NOT NULL,
    valor_matricula numeric(12,2) NOT NULL,
    descuento numeric(12,2) NOT NULL,
    abono numeric(12,2) NOT NULL,
    saldo numeric(12,2) NOT NULL,
    promo boolean NOT NULL,
    autorizacion_imagen boolean NOT NULL,
    acepta_garantia boolean NOT NULL,
    acepta_no_devolucion boolean NOT NULL,
    firma_representante text,
    ci_representante_firma character varying(20),
    firma_director_asesor text,
    ci_director_asesor character varying(20),
    archivo_contrato character varying(100),
    archivo_ficha_firmada character varying(100),
    estado character varying(20) NOT NULL,
    observacion text,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_aula integer,
    id_cliente integer NOT NULL,
    id_curso integer,
    id_empresa integer NOT NULL,
    id_estudiante integer NOT NULL,
    id_representante integer,
    id_usuario_updated integer,
    id_periodo_academico integer NOT NULL
);


--
-- Name: v_cartera_semaforo; Type: VIEW; Schema: cartera; Owner: -
--

CREATE VIEW cartera.v_cartera_semaforo AS
 SELECT cu.id,
    pp.id_empresa,
    fi.id AS id_ficha_inscripcion,
    fi.numero AS numero_ficha,
    estudiante.nombre AS estudiante,
    cu.numero,
    cu.fecha_pago_debito,
    cu.valor,
    cu.valor_pagado,
    (cu.valor - cu.valor_pagado) AS saldo,
    cu.estado,
        CASE
            WHEN ((cu.estado)::text = 'pagada'::text) THEN 'al_dia'::text
            WHEN (cu.fecha_pago_debito < (CURRENT_DATE - '30 days'::interval)) THEN 'critico'::text
            WHEN (cu.fecha_pago_debito < CURRENT_DATE) THEN 'vencido'::text
            WHEN (cu.fecha_pago_debito <= (CURRENT_DATE + '7 days'::interval)) THEN 'proximo'::text
            ELSE 'al_dia'::text
        END AS semaforo
   FROM (((cartera.cuota cu
     JOIN cartera.plan_pago pp ON ((pp.id = cu.id_plan_pago)))
     JOIN matricula.ficha_inscripcion fi ON ((fi.id = pp.id_ficha_inscripcion)))
     JOIN core.partner estudiante ON ((estudiante.id = fi.id_estudiante)))
  WHERE (cu.activo = true);


--
-- Name: empresa; Type: TABLE; Schema: core; Owner: -
--

CREATE TABLE core.empresa (
    id integer NOT NULL,
    ruc character varying(13) NOT NULL,
    razon_social character varying(300),
    nombre_comercial character varying(300),
    direccion text NOT NULL,
    telefono character varying(20),
    email text,
    ciudad character varying(80),
    logo text,
    activa boolean NOT NULL,
    tags public.hstore,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_usuario_updated integer
);


--
-- Name: empresa_id_seq; Type: SEQUENCE; Schema: core; Owner: -
--

ALTER TABLE core.empresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME core.empresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: operador_movil; Type: TABLE; Schema: core; Owner: -
--

CREATE TABLE core.operador_movil (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    comentario character varying(200),
    activo boolean NOT NULL
);


--
-- Name: operador_movil_id_seq; Type: SEQUENCE; Schema: core; Owner: -
--

ALTER TABLE core.operador_movil ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME core.operador_movil_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_id_seq; Type: SEQUENCE; Schema: core; Owner: -
--

ALTER TABLE core.partner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME core.partner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_partner; Type: TABLE; Schema: core; Owner: -
--

CREATE TABLE core.partner_partner (
    id integer NOT NULL,
    relacion character varying(50) NOT NULL,
    principal boolean NOT NULL,
    contacto_emergencia boolean NOT NULL,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_partner_a integer NOT NULL,
    id_partner_b integer NOT NULL,
    id_usuario_updated integer
);


--
-- Name: partner_partner_id_seq; Type: SEQUENCE; Schema: core; Owner: -
--

ALTER TABLE core.partner_partner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME core.partner_partner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_identificacion; Type: TABLE; Schema: core; Owner: -
--

CREATE TABLE core.tipo_identificacion (
    id integer NOT NULL,
    nombre character varying(30) NOT NULL,
    codigo character varying(10),
    activo boolean NOT NULL
);


--
-- Name: tipo_identificacion_id_seq; Type: SEQUENCE; Schema: core; Owner: -
--

ALTER TABLE core.tipo_identificacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME core.tipo_identificacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aula; Type: TABLE; Schema: matricula; Owner: -
--

CREATE TABLE matricula.aula (
    id integer NOT NULL,
    nombre character varying(120) NOT NULL,
    seccion character varying(40),
    jornada character varying(40),
    horario character varying(120),
    hora character varying(80),
    duracion character varying(80),
    capacidad integer NOT NULL,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_empresa integer NOT NULL,
    id_usuario_updated integer,
    id_periodo_academico integer NOT NULL
);


--
-- Name: aula_historial; Type: TABLE; Schema: matricula; Owner: -
--

CREATE TABLE matricula.aula_historial (
    id integer NOT NULL,
    fecha_cambio timestamp with time zone NOT NULL,
    motivo text,
    id_aula_destino integer NOT NULL,
    id_aula_origen integer,
    id_usuario integer,
    id_ficha_inscripcion integer NOT NULL
);


--
-- Name: aula_historial_id_seq; Type: SEQUENCE; Schema: matricula; Owner: -
--

ALTER TABLE matricula.aula_historial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME matricula.aula_historial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aula_id_seq; Type: SEQUENCE; Schema: matricula; Owner: -
--

ALTER TABLE matricula.aula ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME matricula.aula_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: curso; Type: TABLE; Schema: matricula; Owner: -
--

CREATE TABLE matricula.curso (
    id integer NOT NULL,
    nombre character varying(120) NOT NULL,
    grado character varying(60),
    carrera character varying(160),
    universidad character varying(160),
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_empresa integer NOT NULL,
    id_usuario_updated integer
);


--
-- Name: curso_id_seq; Type: SEQUENCE; Schema: matricula; Owner: -
--

ALTER TABLE matricula.curso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME matricula.curso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ficha_inscripcion_id_seq; Type: SEQUENCE; Schema: matricula; Owner: -
--

ALTER TABLE matricula.ficha_inscripcion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME matricula.ficha_inscripcion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: periodo_academico; Type: TABLE; Schema: matricula; Owner: -
--

CREATE TABLE matricula.periodo_academico (
    id integer NOT NULL,
    nombre character varying(120) NOT NULL,
    regimen character varying(60),
    fecha_inicio date,
    fecha_fin date,
    estado character varying(20) NOT NULL,
    activo boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    id_empresa integer NOT NULL,
    id_usuario_updated integer
);


--
-- Name: periodo_academico_id_seq; Type: SEQUENCE; Schema: matricula; Owner: -
--

ALTER TABLE matricula.periodo_academico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME matricula.periodo_academico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: v_ficha_inscripcion; Type: VIEW; Schema: matricula; Owner: -
--

CREATE VIEW matricula.v_ficha_inscripcion AS
 SELECT fi.id,
    fi.numero,
    fi.fecha,
    e.razon_social AS empresa,
    cliente.nombre AS cliente,
    cliente.identificacion AS identificacion_cliente,
    estudiante.nombre AS estudiante,
    estudiante.identificacion AS identificacion_estudiante,
    representante.nombre AS representante,
    representante.identificacion AS identificacion_representante,
    pa.nombre AS periodo,
    c.nombre AS curso,
    a.nombre AS aula,
    fi.colegio,
    fi.carrera,
    fi.universidad,
    fi.valor_total_curso,
    fi.valor_matricula,
    fi.descuento,
    fi.abono,
    fi.saldo,
    fi.estado
   FROM (((((((matricula.ficha_inscripcion fi
     JOIN core.empresa e ON ((e.id = fi.id_empresa)))
     JOIN core.partner cliente ON ((cliente.id = fi.id_cliente)))
     JOIN core.partner estudiante ON ((estudiante.id = fi.id_estudiante)))
     LEFT JOIN core.partner representante ON ((representante.id = fi.id_representante)))
     JOIN matricula.periodo_academico pa ON ((pa.id = fi.id_periodo_academico)))
     LEFT JOIN matricula.curso c ON ((c.id = fi.id_curso)))
     LEFT JOIN matricula.aula a ON ((a.id = fi.id_aula)));


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: asignatura asignatura_id_empresa_codigo_747708b4_uniq; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.asignatura
    ADD CONSTRAINT asignatura_id_empresa_codigo_747708b4_uniq UNIQUE (id_empresa, codigo);


--
-- Name: asignatura asignatura_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.asignatura
    ADD CONSTRAINT asignatura_pkey PRIMARY KEY (id);


--
-- Name: asistencia asistencia_id_planificacion_clase_id_estudiante_cd6f3619_uniq; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.asistencia
    ADD CONSTRAINT asistencia_id_planificacion_clase_id_estudiante_cd6f3619_uniq UNIQUE (id_planificacion_clase, id_estudiante);


--
-- Name: asistencia asistencia_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.asistencia
    ADD CONSTRAINT asistencia_pkey PRIMARY KEY (id);


--
-- Name: banco_pregunta banco_pregunta_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.banco_pregunta
    ADD CONSTRAINT banco_pregunta_pkey PRIMARY KEY (id);


--
-- Name: docente_asignatura docente_asignatura_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.docente_asignatura
    ADD CONSTRAINT docente_asignatura_pkey PRIMARY KEY (id);


--
-- Name: evaluacion evaluacion_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion
    ADD CONSTRAINT evaluacion_pkey PRIMARY KEY (id);


--
-- Name: evaluacion_resultado evaluacion_resultado_id_evaluacion_id_estudiante_0fa04f56_uniq; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion_resultado
    ADD CONSTRAINT evaluacion_resultado_id_evaluacion_id_estudiante_0fa04f56_uniq UNIQUE (id_evaluacion, id_estudiante);


--
-- Name: evaluacion_resultado evaluacion_resultado_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion_resultado
    ADD CONSTRAINT evaluacion_resultado_pkey PRIMARY KEY (id);


--
-- Name: planificacion_clase planificacion_clase_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.planificacion_clase
    ADD CONSTRAINT planificacion_clase_pkey PRIMARY KEY (id);


--
-- Name: pregunta pregunta_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.pregunta
    ADD CONSTRAINT pregunta_pkey PRIMARY KEY (id);


--
-- Name: recurso_clase recurso_clase_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.recurso_clase
    ADD CONSTRAINT recurso_clase_pkey PRIMARY KEY (id);


--
-- Name: subtema subtema_id_tema_orden_f76fdef2_uniq; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.subtema
    ADD CONSTRAINT subtema_id_tema_orden_f76fdef2_uniq UNIQUE (id_tema, orden);


--
-- Name: subtema subtema_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.subtema
    ADD CONSTRAINT subtema_pkey PRIMARY KEY (id);


--
-- Name: tema tema_id_temario_orden_ab09aa97_uniq; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.tema
    ADD CONSTRAINT tema_id_temario_orden_ab09aa97_uniq UNIQUE (id_temario, orden);


--
-- Name: tema tema_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.tema
    ADD CONSTRAINT tema_pkey PRIMARY KEY (id);


--
-- Name: temario temario_pkey; Type: CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.temario
    ADD CONSTRAINT temario_pkey PRIMARY KEY (id);


--
-- Name: log_accion log_accion_pkey; Type: CONSTRAINT; Schema: auditoria; Owner: -
--

ALTER TABLE ONLY auditoria.log_accion
    ADD CONSTRAINT log_accion_pkey PRIMARY KEY (id);


--
-- Name: cuota cuota_id_plan_pago_numero_21c4022b_uniq; Type: CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.cuota
    ADD CONSTRAINT cuota_id_plan_pago_numero_21c4022b_uniq UNIQUE (id_plan_pago, numero);


--
-- Name: cuota cuota_pkey; Type: CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.cuota
    ADD CONSTRAINT cuota_pkey PRIMARY KEY (id);


--
-- Name: forma_pago forma_pago_id_empresa_tipo_c1d5fbe8_uniq; Type: CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.forma_pago
    ADD CONSTRAINT forma_pago_id_empresa_tipo_c1d5fbe8_uniq UNIQUE (id_empresa, tipo);


--
-- Name: forma_pago forma_pago_pkey; Type: CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.forma_pago
    ADD CONSTRAINT forma_pago_pkey PRIMARY KEY (id);


--
-- Name: pago pago_pkey; Type: CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.pago
    ADD CONSTRAINT pago_pkey PRIMARY KEY (id);


--
-- Name: plan_pago plan_pago_id_ficha_inscripcion_key; Type: CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.plan_pago
    ADD CONSTRAINT plan_pago_id_ficha_inscripcion_key UNIQUE (id_ficha_inscripcion);


--
-- Name: plan_pago plan_pago_pkey; Type: CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.plan_pago
    ADD CONSTRAINT plan_pago_pkey PRIMARY KEY (id);


--
-- Name: empresa empresa_pkey; Type: CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.empresa
    ADD CONSTRAINT empresa_pkey PRIMARY KEY (id);


--
-- Name: operador_movil operador_movil_pkey; Type: CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.operador_movil
    ADD CONSTRAINT operador_movil_pkey PRIMARY KEY (id);


--
-- Name: partner partner_identificacion_key; Type: CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.partner
    ADD CONSTRAINT partner_identificacion_key UNIQUE (identificacion);


--
-- Name: partner_partner partner_partner_id_partner_a_id_partner__5e307c39_uniq; Type: CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.partner_partner
    ADD CONSTRAINT partner_partner_id_partner_a_id_partner__5e307c39_uniq UNIQUE (id_partner_a, id_partner_b, relacion);


--
-- Name: partner_partner partner_partner_pkey; Type: CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.partner_partner
    ADD CONSTRAINT partner_partner_pkey PRIMARY KEY (id);


--
-- Name: partner partner_pkey; Type: CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.partner
    ADD CONSTRAINT partner_pkey PRIMARY KEY (id);


--
-- Name: tipo_identificacion tipo_identificacion_pkey; Type: CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.tipo_identificacion
    ADD CONSTRAINT tipo_identificacion_pkey PRIMARY KEY (id);


--
-- Name: aula_historial aula_historial_pkey; Type: CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.aula_historial
    ADD CONSTRAINT aula_historial_pkey PRIMARY KEY (id);


--
-- Name: aula aula_id_periodo_academico_nombre_seccion_975f74a3_uniq; Type: CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.aula
    ADD CONSTRAINT aula_id_periodo_academico_nombre_seccion_975f74a3_uniq UNIQUE (id_periodo_academico, nombre, seccion);


--
-- Name: aula aula_pkey; Type: CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.aula
    ADD CONSTRAINT aula_pkey PRIMARY KEY (id);


--
-- Name: curso curso_pkey; Type: CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.curso
    ADD CONSTRAINT curso_pkey PRIMARY KEY (id);


--
-- Name: ficha_inscripcion ficha_inscripcion_id_empresa_numero_006ca28c_uniq; Type: CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.ficha_inscripcion
    ADD CONSTRAINT ficha_inscripcion_id_empresa_numero_006ca28c_uniq UNIQUE (id_empresa, numero);


--
-- Name: ficha_inscripcion ficha_inscripcion_pkey; Type: CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.ficha_inscripcion
    ADD CONSTRAINT ficha_inscripcion_pkey PRIMARY KEY (id);


--
-- Name: periodo_academico periodo_academico_id_empresa_nombre_a7c1ae72_uniq; Type: CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.periodo_academico
    ADD CONSTRAINT periodo_academico_id_empresa_nombre_a7c1ae72_uniq UNIQUE (id_empresa, nombre);


--
-- Name: periodo_academico periodo_academico_pkey; Type: CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.periodo_academico
    ADD CONSTRAINT periodo_academico_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: asignatura_id_empresa_2f4362ff; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX asignatura_id_empresa_2f4362ff ON academico.asignatura USING btree (id_empresa);


--
-- Name: asignatura_id_usuario_updated_21b0d390; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX asignatura_id_usuario_updated_21b0d390 ON academico.asignatura USING btree (id_usuario_updated);


--
-- Name: asistencia_id_estudiante_f6d8edf7; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX asistencia_id_estudiante_f6d8edf7 ON academico.asistencia USING btree (id_estudiante);


--
-- Name: asistencia_id_planificacion_clase_b322a709; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX asistencia_id_planificacion_clase_b322a709 ON academico.asistencia USING btree (id_planificacion_clase);


--
-- Name: asistencia_id_registrado_por_2da45f0f; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX asistencia_id_registrado_por_2da45f0f ON academico.asistencia USING btree (id_registrado_por);


--
-- Name: asistencia_id_usuario_updated_2c48eb17; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX asistencia_id_usuario_updated_2c48eb17 ON academico.asistencia USING btree (id_usuario_updated);


--
-- Name: banco_pregunta_id_asignatura_ef7fb1f7; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX banco_pregunta_id_asignatura_ef7fb1f7 ON academico.banco_pregunta USING btree (id_asignatura);


--
-- Name: banco_pregunta_id_empresa_08825e19; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX banco_pregunta_id_empresa_08825e19 ON academico.banco_pregunta USING btree (id_empresa);


--
-- Name: banco_pregunta_id_subtema_a4f192d4; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX banco_pregunta_id_subtema_a4f192d4 ON academico.banco_pregunta USING btree (id_subtema);


--
-- Name: banco_pregunta_id_tema_ca8911b6; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX banco_pregunta_id_tema_ca8911b6 ON academico.banco_pregunta USING btree (id_tema);


--
-- Name: banco_pregunta_id_usuario_updated_fd14200a; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX banco_pregunta_id_usuario_updated_fd14200a ON academico.banco_pregunta USING btree (id_usuario_updated);


--
-- Name: docente_asignatura_id_asignatura_f439e362; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX docente_asignatura_id_asignatura_f439e362 ON academico.docente_asignatura USING btree (id_asignatura);


--
-- Name: docente_asignatura_id_aula_017352f0; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX docente_asignatura_id_aula_017352f0 ON academico.docente_asignatura USING btree (id_aula);


--
-- Name: docente_asignatura_id_docente_facf963b; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX docente_asignatura_id_docente_facf963b ON academico.docente_asignatura USING btree (id_docente);


--
-- Name: docente_asignatura_id_empresa_4db8c600; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX docente_asignatura_id_empresa_4db8c600 ON academico.docente_asignatura USING btree (id_empresa);


--
-- Name: docente_asignatura_id_periodo_academico_8bab751b; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX docente_asignatura_id_periodo_academico_8bab751b ON academico.docente_asignatura USING btree (id_periodo_academico);


--
-- Name: docente_asignatura_id_usuario_updated_1d3805a9; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX docente_asignatura_id_usuario_updated_1d3805a9 ON academico.docente_asignatura USING btree (id_usuario_updated);


--
-- Name: evaluacion_id_asignatura_2a78f67a; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX evaluacion_id_asignatura_2a78f67a ON academico.evaluacion USING btree (id_asignatura);


--
-- Name: evaluacion_id_creado_por_274b52d9; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX evaluacion_id_creado_por_274b52d9 ON academico.evaluacion USING btree (id_creado_por);


--
-- Name: evaluacion_id_empresa_87e54e0e; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX evaluacion_id_empresa_87e54e0e ON academico.evaluacion USING btree (id_empresa);


--
-- Name: evaluacion_id_planificacion_clase_2e8f286b; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX evaluacion_id_planificacion_clase_2e8f286b ON academico.evaluacion USING btree (id_planificacion_clase);


--
-- Name: evaluacion_id_tema_90b77e12; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX evaluacion_id_tema_90b77e12 ON academico.evaluacion USING btree (id_tema);


--
-- Name: evaluacion_id_usuario_updated_8ad54e22; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX evaluacion_id_usuario_updated_8ad54e22 ON academico.evaluacion USING btree (id_usuario_updated);


--
-- Name: evaluacion_resultado_id_estudiante_70dc80a6; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX evaluacion_resultado_id_estudiante_70dc80a6 ON academico.evaluacion_resultado USING btree (id_estudiante);


--
-- Name: evaluacion_resultado_id_evaluacion_cc424105; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX evaluacion_resultado_id_evaluacion_cc424105 ON academico.evaluacion_resultado USING btree (id_evaluacion);


--
-- Name: evaluacion_resultado_id_usuario_updated_4bfabfed; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX evaluacion_resultado_id_usuario_updated_4bfabfed ON academico.evaluacion_resultado USING btree (id_usuario_updated);


--
-- Name: planificacion_clase_id_asignatura_7bd42319; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX planificacion_clase_id_asignatura_7bd42319 ON academico.planificacion_clase USING btree (id_asignatura);


--
-- Name: planificacion_clase_id_aula_89710d33; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX planificacion_clase_id_aula_89710d33 ON academico.planificacion_clase USING btree (id_aula);


--
-- Name: planificacion_clase_id_docente_0c800594; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX planificacion_clase_id_docente_0c800594 ON academico.planificacion_clase USING btree (id_docente);


--
-- Name: planificacion_clase_id_empresa_ffc176b9; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX planificacion_clase_id_empresa_ffc176b9 ON academico.planificacion_clase USING btree (id_empresa);


--
-- Name: planificacion_clase_id_revisado_por_4a04f986; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX planificacion_clase_id_revisado_por_4a04f986 ON academico.planificacion_clase USING btree (id_revisado_por);


--
-- Name: planificacion_clase_id_subtema_3306781f; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX planificacion_clase_id_subtema_3306781f ON academico.planificacion_clase USING btree (id_subtema);


--
-- Name: planificacion_clase_id_tema_8fc3674c; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX planificacion_clase_id_tema_8fc3674c ON academico.planificacion_clase USING btree (id_tema);


--
-- Name: planificacion_clase_id_usuario_updated_83000bf0; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX planificacion_clase_id_usuario_updated_83000bf0 ON academico.planificacion_clase USING btree (id_usuario_updated);


--
-- Name: pregunta_id_banco_pregunta_14560991; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX pregunta_id_banco_pregunta_14560991 ON academico.pregunta USING btree (id_banco_pregunta);


--
-- Name: pregunta_id_creado_por_d1035d8f; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX pregunta_id_creado_por_d1035d8f ON academico.pregunta USING btree (id_creado_por);


--
-- Name: pregunta_id_revisado_por_3d5845c1; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX pregunta_id_revisado_por_3d5845c1 ON academico.pregunta USING btree (id_revisado_por);


--
-- Name: pregunta_id_usuario_updated_a79d5e74; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX pregunta_id_usuario_updated_a79d5e74 ON academico.pregunta USING btree (id_usuario_updated);


--
-- Name: recurso_clase_id_creado_por_794b9d12; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX recurso_clase_id_creado_por_794b9d12 ON academico.recurso_clase USING btree (id_creado_por);


--
-- Name: recurso_clase_id_planificacion_clase_19298d56; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX recurso_clase_id_planificacion_clase_19298d56 ON academico.recurso_clase USING btree (id_planificacion_clase);


--
-- Name: recurso_clase_id_usuario_updated_d77014eb; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX recurso_clase_id_usuario_updated_d77014eb ON academico.recurso_clase USING btree (id_usuario_updated);


--
-- Name: subtema_id_tema_28749374; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX subtema_id_tema_28749374 ON academico.subtema USING btree (id_tema);


--
-- Name: subtema_id_usuario_updated_1f861657; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX subtema_id_usuario_updated_1f861657 ON academico.subtema USING btree (id_usuario_updated);


--
-- Name: tema_id_temario_d112ebb2; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX tema_id_temario_d112ebb2 ON academico.tema USING btree (id_temario);


--
-- Name: tema_id_usuario_updated_b72af41f; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX tema_id_usuario_updated_b72af41f ON academico.tema USING btree (id_usuario_updated);


--
-- Name: temario_id_asignatura_b11c2486; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX temario_id_asignatura_b11c2486 ON academico.temario USING btree (id_asignatura);


--
-- Name: temario_id_empresa_fe575339; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX temario_id_empresa_fe575339 ON academico.temario USING btree (id_empresa);


--
-- Name: temario_id_periodo_academico_4ad53fde; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX temario_id_periodo_academico_4ad53fde ON academico.temario USING btree (id_periodo_academico);


--
-- Name: temario_id_usuario_updated_37cbd0da; Type: INDEX; Schema: academico; Owner: -
--

CREATE INDEX temario_id_usuario_updated_37cbd0da ON academico.temario USING btree (id_usuario_updated);


--
-- Name: log_accion_id_empresa_4fe19b25; Type: INDEX; Schema: auditoria; Owner: -
--

CREATE INDEX log_accion_id_empresa_4fe19b25 ON auditoria.log_accion USING btree (id_empresa);


--
-- Name: log_accion_id_usuario_72dbc939; Type: INDEX; Schema: auditoria; Owner: -
--

CREATE INDEX log_accion_id_usuario_72dbc939 ON auditoria.log_accion USING btree (id_usuario);


--
-- Name: cuota_id_plan_pago_45e96ace; Type: INDEX; Schema: cartera; Owner: -
--

CREATE INDEX cuota_id_plan_pago_45e96ace ON cartera.cuota USING btree (id_plan_pago);


--
-- Name: cuota_id_usuario_updated_eb9c5b70; Type: INDEX; Schema: cartera; Owner: -
--

CREATE INDEX cuota_id_usuario_updated_eb9c5b70 ON cartera.cuota USING btree (id_usuario_updated);


--
-- Name: forma_pago_id_empresa_fd1bd075; Type: INDEX; Schema: cartera; Owner: -
--

CREATE INDEX forma_pago_id_empresa_fd1bd075 ON cartera.forma_pago USING btree (id_empresa);


--
-- Name: forma_pago_id_usuario_updated_0fcda64b; Type: INDEX; Schema: cartera; Owner: -
--

CREATE INDEX forma_pago_id_usuario_updated_0fcda64b ON cartera.forma_pago USING btree (id_usuario_updated);


--
-- Name: pago_id_cuota_d30464b0; Type: INDEX; Schema: cartera; Owner: -
--

CREATE INDEX pago_id_cuota_d30464b0 ON cartera.pago USING btree (id_cuota);


--
-- Name: pago_id_empresa_422958ca; Type: INDEX; Schema: cartera; Owner: -
--

CREATE INDEX pago_id_empresa_422958ca ON cartera.pago USING btree (id_empresa);


--
-- Name: pago_id_forma_pago_d30c8c49; Type: INDEX; Schema: cartera; Owner: -
--

CREATE INDEX pago_id_forma_pago_d30c8c49 ON cartera.pago USING btree (id_forma_pago);


--
-- Name: pago_id_usuario_7ad17a52; Type: INDEX; Schema: cartera; Owner: -
--

CREATE INDEX pago_id_usuario_7ad17a52 ON cartera.pago USING btree (id_usuario);


--
-- Name: pago_id_usuario_updated_76a025b2; Type: INDEX; Schema: cartera; Owner: -
--

CREATE INDEX pago_id_usuario_updated_76a025b2 ON cartera.pago USING btree (id_usuario_updated);


--
-- Name: plan_pago_id_empresa_08264011; Type: INDEX; Schema: cartera; Owner: -
--

CREATE INDEX plan_pago_id_empresa_08264011 ON cartera.plan_pago USING btree (id_empresa);


--
-- Name: plan_pago_id_usuario_updated_b1d87e9c; Type: INDEX; Schema: cartera; Owner: -
--

CREATE INDEX plan_pago_id_usuario_updated_b1d87e9c ON cartera.plan_pago USING btree (id_usuario_updated);


--
-- Name: empresa_id_usuario_updated_45ad5f7b; Type: INDEX; Schema: core; Owner: -
--

CREATE INDEX empresa_id_usuario_updated_45ad5f7b ON core.empresa USING btree (id_usuario_updated);


--
-- Name: partner_id_empresa_b2966e28; Type: INDEX; Schema: core; Owner: -
--

CREATE INDEX partner_id_empresa_b2966e28 ON core.partner USING btree (id_empresa);


--
-- Name: partner_id_operador_movil_73e8eb12; Type: INDEX; Schema: core; Owner: -
--

CREATE INDEX partner_id_operador_movil_73e8eb12 ON core.partner USING btree (id_operador_movil);


--
-- Name: partner_id_tipo_identificacion_fd7f4187; Type: INDEX; Schema: core; Owner: -
--

CREATE INDEX partner_id_tipo_identificacion_fd7f4187 ON core.partner USING btree (id_tipo_identificacion);


--
-- Name: partner_id_usuario_updated_db6fb1a3; Type: INDEX; Schema: core; Owner: -
--

CREATE INDEX partner_id_usuario_updated_db6fb1a3 ON core.partner USING btree (id_usuario_updated);


--
-- Name: partner_identificacion_c43c245a_like; Type: INDEX; Schema: core; Owner: -
--

CREATE INDEX partner_identificacion_c43c245a_like ON core.partner USING btree (identificacion varchar_pattern_ops);


--
-- Name: partner_partner_id_partner_a_3024f60e; Type: INDEX; Schema: core; Owner: -
--

CREATE INDEX partner_partner_id_partner_a_3024f60e ON core.partner_partner USING btree (id_partner_a);


--
-- Name: partner_partner_id_partner_b_e55dcd07; Type: INDEX; Schema: core; Owner: -
--

CREATE INDEX partner_partner_id_partner_b_e55dcd07 ON core.partner_partner USING btree (id_partner_b);


--
-- Name: partner_partner_id_usuario_updated_a3264d54; Type: INDEX; Schema: core; Owner: -
--

CREATE INDEX partner_partner_id_usuario_updated_a3264d54 ON core.partner_partner USING btree (id_usuario_updated);


--
-- Name: aula_historial_id_aula_destino_a08e33ef; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX aula_historial_id_aula_destino_a08e33ef ON matricula.aula_historial USING btree (id_aula_destino);


--
-- Name: aula_historial_id_aula_origen_42fd2b92; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX aula_historial_id_aula_origen_42fd2b92 ON matricula.aula_historial USING btree (id_aula_origen);


--
-- Name: aula_historial_id_ficha_inscripcion_a55ed701; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX aula_historial_id_ficha_inscripcion_a55ed701 ON matricula.aula_historial USING btree (id_ficha_inscripcion);


--
-- Name: aula_historial_id_usuario_8fa0ee43; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX aula_historial_id_usuario_8fa0ee43 ON matricula.aula_historial USING btree (id_usuario);


--
-- Name: aula_id_empresa_fb0e40be; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX aula_id_empresa_fb0e40be ON matricula.aula USING btree (id_empresa);


--
-- Name: aula_id_periodo_academico_6afe15eb; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX aula_id_periodo_academico_6afe15eb ON matricula.aula USING btree (id_periodo_academico);


--
-- Name: aula_id_usuario_updated_6b07e92f; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX aula_id_usuario_updated_6b07e92f ON matricula.aula USING btree (id_usuario_updated);


--
-- Name: curso_id_empresa_f06c8ee6; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX curso_id_empresa_f06c8ee6 ON matricula.curso USING btree (id_empresa);


--
-- Name: curso_id_usuario_updated_c7680f48; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX curso_id_usuario_updated_c7680f48 ON matricula.curso USING btree (id_usuario_updated);


--
-- Name: ficha_inscripcion_id_aula_fe0c50d6; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX ficha_inscripcion_id_aula_fe0c50d6 ON matricula.ficha_inscripcion USING btree (id_aula);


--
-- Name: ficha_inscripcion_id_cliente_0b9f36f7; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX ficha_inscripcion_id_cliente_0b9f36f7 ON matricula.ficha_inscripcion USING btree (id_cliente);


--
-- Name: ficha_inscripcion_id_curso_6e014733; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX ficha_inscripcion_id_curso_6e014733 ON matricula.ficha_inscripcion USING btree (id_curso);


--
-- Name: ficha_inscripcion_id_empresa_53617669; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX ficha_inscripcion_id_empresa_53617669 ON matricula.ficha_inscripcion USING btree (id_empresa);


--
-- Name: ficha_inscripcion_id_estudiante_2397b139; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX ficha_inscripcion_id_estudiante_2397b139 ON matricula.ficha_inscripcion USING btree (id_estudiante);


--
-- Name: ficha_inscripcion_id_periodo_academico_36e67ba2; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX ficha_inscripcion_id_periodo_academico_36e67ba2 ON matricula.ficha_inscripcion USING btree (id_periodo_academico);


--
-- Name: ficha_inscripcion_id_representante_c15575d6; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX ficha_inscripcion_id_representante_c15575d6 ON matricula.ficha_inscripcion USING btree (id_representante);


--
-- Name: ficha_inscripcion_id_usuario_updated_bf5857b9; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX ficha_inscripcion_id_usuario_updated_bf5857b9 ON matricula.ficha_inscripcion USING btree (id_usuario_updated);


--
-- Name: periodo_academico_id_empresa_2d084f06; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX periodo_academico_id_empresa_2d084f06 ON matricula.periodo_academico USING btree (id_empresa);


--
-- Name: periodo_academico_id_usuario_updated_c5dfbe6f; Type: INDEX; Schema: matricula; Owner: -
--

CREATE INDEX periodo_academico_id_usuario_updated_c5dfbe6f ON matricula.periodo_academico USING btree (id_usuario_updated);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: asignatura asignatura_id_empresa_2f4362ff_fk_empresa_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.asignatura
    ADD CONSTRAINT asignatura_id_empresa_2f4362ff_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: asignatura asignatura_id_usuario_updated_21b0d390_fk_auth_user_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.asignatura
    ADD CONSTRAINT asignatura_id_usuario_updated_21b0d390_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: asistencia asistencia_id_estudiante_f6d8edf7_fk_partner_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.asistencia
    ADD CONSTRAINT asistencia_id_estudiante_f6d8edf7_fk_partner_id FOREIGN KEY (id_estudiante) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: asistencia asistencia_id_planificacion_cla_b322a709_fk_planifica; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.asistencia
    ADD CONSTRAINT asistencia_id_planificacion_cla_b322a709_fk_planifica FOREIGN KEY (id_planificacion_clase) REFERENCES academico.planificacion_clase(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: asistencia asistencia_id_registrado_por_2da45f0f_fk_partner_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.asistencia
    ADD CONSTRAINT asistencia_id_registrado_por_2da45f0f_fk_partner_id FOREIGN KEY (id_registrado_por) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: asistencia asistencia_id_usuario_updated_2c48eb17_fk_auth_user_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.asistencia
    ADD CONSTRAINT asistencia_id_usuario_updated_2c48eb17_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: banco_pregunta banco_pregunta_id_asignatura_ef7fb1f7_fk_asignatura_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.banco_pregunta
    ADD CONSTRAINT banco_pregunta_id_asignatura_ef7fb1f7_fk_asignatura_id FOREIGN KEY (id_asignatura) REFERENCES academico.asignatura(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: banco_pregunta banco_pregunta_id_empresa_08825e19_fk_empresa_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.banco_pregunta
    ADD CONSTRAINT banco_pregunta_id_empresa_08825e19_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: banco_pregunta banco_pregunta_id_subtema_a4f192d4_fk_subtema_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.banco_pregunta
    ADD CONSTRAINT banco_pregunta_id_subtema_a4f192d4_fk_subtema_id FOREIGN KEY (id_subtema) REFERENCES academico.subtema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: banco_pregunta banco_pregunta_id_tema_ca8911b6_fk_tema_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.banco_pregunta
    ADD CONSTRAINT banco_pregunta_id_tema_ca8911b6_fk_tema_id FOREIGN KEY (id_tema) REFERENCES academico.tema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: banco_pregunta banco_pregunta_id_usuario_updated_fd14200a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.banco_pregunta
    ADD CONSTRAINT banco_pregunta_id_usuario_updated_fd14200a_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: docente_asignatura docente_asignatura_id_asignatura_f439e362_fk_asignatura_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.docente_asignatura
    ADD CONSTRAINT docente_asignatura_id_asignatura_f439e362_fk_asignatura_id FOREIGN KEY (id_asignatura) REFERENCES academico.asignatura(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: docente_asignatura docente_asignatura_id_aula_017352f0_fk_aula_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.docente_asignatura
    ADD CONSTRAINT docente_asignatura_id_aula_017352f0_fk_aula_id FOREIGN KEY (id_aula) REFERENCES matricula.aula(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: docente_asignatura docente_asignatura_id_docente_facf963b_fk_partner_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.docente_asignatura
    ADD CONSTRAINT docente_asignatura_id_docente_facf963b_fk_partner_id FOREIGN KEY (id_docente) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: docente_asignatura docente_asignatura_id_empresa_4db8c600_fk_empresa_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.docente_asignatura
    ADD CONSTRAINT docente_asignatura_id_empresa_4db8c600_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: docente_asignatura docente_asignatura_id_periodo_academico_8bab751b_fk_periodo_a; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.docente_asignatura
    ADD CONSTRAINT docente_asignatura_id_periodo_academico_8bab751b_fk_periodo_a FOREIGN KEY (id_periodo_academico) REFERENCES matricula.periodo_academico(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: docente_asignatura docente_asignatura_id_usuario_updated_1d3805a9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.docente_asignatura
    ADD CONSTRAINT docente_asignatura_id_usuario_updated_1d3805a9_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluacion evaluacion_id_asignatura_2a78f67a_fk_asignatura_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion
    ADD CONSTRAINT evaluacion_id_asignatura_2a78f67a_fk_asignatura_id FOREIGN KEY (id_asignatura) REFERENCES academico.asignatura(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluacion evaluacion_id_creado_por_274b52d9_fk_partner_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion
    ADD CONSTRAINT evaluacion_id_creado_por_274b52d9_fk_partner_id FOREIGN KEY (id_creado_por) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluacion evaluacion_id_empresa_87e54e0e_fk_empresa_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion
    ADD CONSTRAINT evaluacion_id_empresa_87e54e0e_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluacion evaluacion_id_planificacion_cla_2e8f286b_fk_planifica; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion
    ADD CONSTRAINT evaluacion_id_planificacion_cla_2e8f286b_fk_planifica FOREIGN KEY (id_planificacion_clase) REFERENCES academico.planificacion_clase(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluacion evaluacion_id_tema_90b77e12_fk_tema_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion
    ADD CONSTRAINT evaluacion_id_tema_90b77e12_fk_tema_id FOREIGN KEY (id_tema) REFERENCES academico.tema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluacion evaluacion_id_usuario_updated_8ad54e22_fk_auth_user_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion
    ADD CONSTRAINT evaluacion_id_usuario_updated_8ad54e22_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluacion_resultado evaluacion_resultado_id_estudiante_70dc80a6_fk_partner_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion_resultado
    ADD CONSTRAINT evaluacion_resultado_id_estudiante_70dc80a6_fk_partner_id FOREIGN KEY (id_estudiante) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluacion_resultado evaluacion_resultado_id_evaluacion_cc424105_fk_evaluacion_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion_resultado
    ADD CONSTRAINT evaluacion_resultado_id_evaluacion_cc424105_fk_evaluacion_id FOREIGN KEY (id_evaluacion) REFERENCES academico.evaluacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evaluacion_resultado evaluacion_resultado_id_usuario_updated_4bfabfed_fk_auth_user; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.evaluacion_resultado
    ADD CONSTRAINT evaluacion_resultado_id_usuario_updated_4bfabfed_fk_auth_user FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: planificacion_clase planificacion_clase_id_asignatura_7bd42319_fk_asignatura_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.planificacion_clase
    ADD CONSTRAINT planificacion_clase_id_asignatura_7bd42319_fk_asignatura_id FOREIGN KEY (id_asignatura) REFERENCES academico.asignatura(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: planificacion_clase planificacion_clase_id_aula_89710d33_fk_aula_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.planificacion_clase
    ADD CONSTRAINT planificacion_clase_id_aula_89710d33_fk_aula_id FOREIGN KEY (id_aula) REFERENCES matricula.aula(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: planificacion_clase planificacion_clase_id_docente_0c800594_fk_partner_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.planificacion_clase
    ADD CONSTRAINT planificacion_clase_id_docente_0c800594_fk_partner_id FOREIGN KEY (id_docente) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: planificacion_clase planificacion_clase_id_empresa_ffc176b9_fk_empresa_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.planificacion_clase
    ADD CONSTRAINT planificacion_clase_id_empresa_ffc176b9_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: planificacion_clase planificacion_clase_id_revisado_por_4a04f986_fk_partner_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.planificacion_clase
    ADD CONSTRAINT planificacion_clase_id_revisado_por_4a04f986_fk_partner_id FOREIGN KEY (id_revisado_por) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: planificacion_clase planificacion_clase_id_subtema_3306781f_fk_subtema_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.planificacion_clase
    ADD CONSTRAINT planificacion_clase_id_subtema_3306781f_fk_subtema_id FOREIGN KEY (id_subtema) REFERENCES academico.subtema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: planificacion_clase planificacion_clase_id_tema_8fc3674c_fk_tema_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.planificacion_clase
    ADD CONSTRAINT planificacion_clase_id_tema_8fc3674c_fk_tema_id FOREIGN KEY (id_tema) REFERENCES academico.tema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: planificacion_clase planificacion_clase_id_usuario_updated_83000bf0_fk_auth_user_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.planificacion_clase
    ADD CONSTRAINT planificacion_clase_id_usuario_updated_83000bf0_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pregunta pregunta_id_banco_pregunta_14560991_fk_banco_pregunta_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.pregunta
    ADD CONSTRAINT pregunta_id_banco_pregunta_14560991_fk_banco_pregunta_id FOREIGN KEY (id_banco_pregunta) REFERENCES academico.banco_pregunta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pregunta pregunta_id_creado_por_d1035d8f_fk_partner_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.pregunta
    ADD CONSTRAINT pregunta_id_creado_por_d1035d8f_fk_partner_id FOREIGN KEY (id_creado_por) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pregunta pregunta_id_revisado_por_3d5845c1_fk_partner_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.pregunta
    ADD CONSTRAINT pregunta_id_revisado_por_3d5845c1_fk_partner_id FOREIGN KEY (id_revisado_por) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pregunta pregunta_id_usuario_updated_a79d5e74_fk_auth_user_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.pregunta
    ADD CONSTRAINT pregunta_id_usuario_updated_a79d5e74_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recurso_clase recurso_clase_id_creado_por_794b9d12_fk_partner_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.recurso_clase
    ADD CONSTRAINT recurso_clase_id_creado_por_794b9d12_fk_partner_id FOREIGN KEY (id_creado_por) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recurso_clase recurso_clase_id_planificacion_cla_19298d56_fk_planifica; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.recurso_clase
    ADD CONSTRAINT recurso_clase_id_planificacion_cla_19298d56_fk_planifica FOREIGN KEY (id_planificacion_clase) REFERENCES academico.planificacion_clase(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recurso_clase recurso_clase_id_usuario_updated_d77014eb_fk_auth_user_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.recurso_clase
    ADD CONSTRAINT recurso_clase_id_usuario_updated_d77014eb_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: subtema subtema_id_tema_28749374_fk_tema_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.subtema
    ADD CONSTRAINT subtema_id_tema_28749374_fk_tema_id FOREIGN KEY (id_tema) REFERENCES academico.tema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: subtema subtema_id_usuario_updated_1f861657_fk_auth_user_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.subtema
    ADD CONSTRAINT subtema_id_usuario_updated_1f861657_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tema tema_id_temario_d112ebb2_fk_temario_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.tema
    ADD CONSTRAINT tema_id_temario_d112ebb2_fk_temario_id FOREIGN KEY (id_temario) REFERENCES academico.temario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tema tema_id_usuario_updated_b72af41f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.tema
    ADD CONSTRAINT tema_id_usuario_updated_b72af41f_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: temario temario_id_asignatura_b11c2486_fk_asignatura_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.temario
    ADD CONSTRAINT temario_id_asignatura_b11c2486_fk_asignatura_id FOREIGN KEY (id_asignatura) REFERENCES academico.asignatura(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: temario temario_id_empresa_fe575339_fk_empresa_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.temario
    ADD CONSTRAINT temario_id_empresa_fe575339_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: temario temario_id_periodo_academico_4ad53fde_fk_periodo_academico_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.temario
    ADD CONSTRAINT temario_id_periodo_academico_4ad53fde_fk_periodo_academico_id FOREIGN KEY (id_periodo_academico) REFERENCES matricula.periodo_academico(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: temario temario_id_usuario_updated_37cbd0da_fk_auth_user_id; Type: FK CONSTRAINT; Schema: academico; Owner: -
--

ALTER TABLE ONLY academico.temario
    ADD CONSTRAINT temario_id_usuario_updated_37cbd0da_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: log_accion log_accion_id_empresa_4fe19b25_fk_empresa_id; Type: FK CONSTRAINT; Schema: auditoria; Owner: -
--

ALTER TABLE ONLY auditoria.log_accion
    ADD CONSTRAINT log_accion_id_empresa_4fe19b25_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: log_accion log_accion_id_usuario_72dbc939_fk_auth_user_id; Type: FK CONSTRAINT; Schema: auditoria; Owner: -
--

ALTER TABLE ONLY auditoria.log_accion
    ADD CONSTRAINT log_accion_id_usuario_72dbc939_fk_auth_user_id FOREIGN KEY (id_usuario) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cuota cuota_id_plan_pago_45e96ace_fk_plan_pago_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.cuota
    ADD CONSTRAINT cuota_id_plan_pago_45e96ace_fk_plan_pago_id FOREIGN KEY (id_plan_pago) REFERENCES cartera.plan_pago(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cuota cuota_id_usuario_updated_eb9c5b70_fk_auth_user_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.cuota
    ADD CONSTRAINT cuota_id_usuario_updated_eb9c5b70_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forma_pago forma_pago_id_empresa_fd1bd075_fk_empresa_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.forma_pago
    ADD CONSTRAINT forma_pago_id_empresa_fd1bd075_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forma_pago forma_pago_id_usuario_updated_0fcda64b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.forma_pago
    ADD CONSTRAINT forma_pago_id_usuario_updated_0fcda64b_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pago pago_id_cuota_d30464b0_fk_cuota_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.pago
    ADD CONSTRAINT pago_id_cuota_d30464b0_fk_cuota_id FOREIGN KEY (id_cuota) REFERENCES cartera.cuota(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pago pago_id_empresa_422958ca_fk_empresa_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.pago
    ADD CONSTRAINT pago_id_empresa_422958ca_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pago pago_id_forma_pago_d30c8c49_fk_forma_pago_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.pago
    ADD CONSTRAINT pago_id_forma_pago_d30c8c49_fk_forma_pago_id FOREIGN KEY (id_forma_pago) REFERENCES cartera.forma_pago(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pago pago_id_usuario_7ad17a52_fk_auth_user_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.pago
    ADD CONSTRAINT pago_id_usuario_7ad17a52_fk_auth_user_id FOREIGN KEY (id_usuario) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pago pago_id_usuario_updated_76a025b2_fk_auth_user_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.pago
    ADD CONSTRAINT pago_id_usuario_updated_76a025b2_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: plan_pago plan_pago_id_empresa_08264011_fk_empresa_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.plan_pago
    ADD CONSTRAINT plan_pago_id_empresa_08264011_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: plan_pago plan_pago_id_ficha_inscripcion_a40c3b49_fk_ficha_inscripcion_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.plan_pago
    ADD CONSTRAINT plan_pago_id_ficha_inscripcion_a40c3b49_fk_ficha_inscripcion_id FOREIGN KEY (id_ficha_inscripcion) REFERENCES matricula.ficha_inscripcion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: plan_pago plan_pago_id_usuario_updated_b1d87e9c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: cartera; Owner: -
--

ALTER TABLE ONLY cartera.plan_pago
    ADD CONSTRAINT plan_pago_id_usuario_updated_b1d87e9c_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: empresa empresa_id_usuario_updated_45ad5f7b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.empresa
    ADD CONSTRAINT empresa_id_usuario_updated_45ad5f7b_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: partner partner_id_empresa_b2966e28_fk_empresa_id; Type: FK CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.partner
    ADD CONSTRAINT partner_id_empresa_b2966e28_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: partner partner_id_operador_movil_73e8eb12_fk_operador_movil_id; Type: FK CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.partner
    ADD CONSTRAINT partner_id_operador_movil_73e8eb12_fk_operador_movil_id FOREIGN KEY (id_operador_movil) REFERENCES core.operador_movil(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: partner partner_id_tipo_identificaci_fd7f4187_fk_tipo_iden; Type: FK CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.partner
    ADD CONSTRAINT partner_id_tipo_identificaci_fd7f4187_fk_tipo_iden FOREIGN KEY (id_tipo_identificacion) REFERENCES core.tipo_identificacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: partner partner_id_usuario_updated_db6fb1a3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.partner
    ADD CONSTRAINT partner_id_usuario_updated_db6fb1a3_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: partner_partner partner_partner_id_partner_a_3024f60e_fk_partner_id; Type: FK CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.partner_partner
    ADD CONSTRAINT partner_partner_id_partner_a_3024f60e_fk_partner_id FOREIGN KEY (id_partner_a) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: partner_partner partner_partner_id_partner_b_e55dcd07_fk_partner_id; Type: FK CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.partner_partner
    ADD CONSTRAINT partner_partner_id_partner_b_e55dcd07_fk_partner_id FOREIGN KEY (id_partner_b) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: partner_partner partner_partner_id_usuario_updated_a3264d54_fk_auth_user_id; Type: FK CONSTRAINT; Schema: core; Owner: -
--

ALTER TABLE ONLY core.partner_partner
    ADD CONSTRAINT partner_partner_id_usuario_updated_a3264d54_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aula_historial aula_historial_id_aula_destino_a08e33ef_fk_aula_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.aula_historial
    ADD CONSTRAINT aula_historial_id_aula_destino_a08e33ef_fk_aula_id FOREIGN KEY (id_aula_destino) REFERENCES matricula.aula(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aula_historial aula_historial_id_aula_origen_42fd2b92_fk_aula_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.aula_historial
    ADD CONSTRAINT aula_historial_id_aula_origen_42fd2b92_fk_aula_id FOREIGN KEY (id_aula_origen) REFERENCES matricula.aula(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aula_historial aula_historial_id_ficha_inscripcion_a55ed701_fk_ficha_ins; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.aula_historial
    ADD CONSTRAINT aula_historial_id_ficha_inscripcion_a55ed701_fk_ficha_ins FOREIGN KEY (id_ficha_inscripcion) REFERENCES matricula.ficha_inscripcion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aula_historial aula_historial_id_usuario_8fa0ee43_fk_auth_user_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.aula_historial
    ADD CONSTRAINT aula_historial_id_usuario_8fa0ee43_fk_auth_user_id FOREIGN KEY (id_usuario) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aula aula_id_empresa_fb0e40be_fk_empresa_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.aula
    ADD CONSTRAINT aula_id_empresa_fb0e40be_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aula aula_id_periodo_academico_6afe15eb_fk_periodo_academico_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.aula
    ADD CONSTRAINT aula_id_periodo_academico_6afe15eb_fk_periodo_academico_id FOREIGN KEY (id_periodo_academico) REFERENCES matricula.periodo_academico(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aula aula_id_usuario_updated_6b07e92f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.aula
    ADD CONSTRAINT aula_id_usuario_updated_6b07e92f_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: curso curso_id_empresa_f06c8ee6_fk_empresa_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.curso
    ADD CONSTRAINT curso_id_empresa_f06c8ee6_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: curso curso_id_usuario_updated_c7680f48_fk_auth_user_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.curso
    ADD CONSTRAINT curso_id_usuario_updated_c7680f48_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ficha_inscripcion ficha_inscripcion_id_aula_fe0c50d6_fk_aula_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.ficha_inscripcion
    ADD CONSTRAINT ficha_inscripcion_id_aula_fe0c50d6_fk_aula_id FOREIGN KEY (id_aula) REFERENCES matricula.aula(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ficha_inscripcion ficha_inscripcion_id_cliente_0b9f36f7_fk_partner_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.ficha_inscripcion
    ADD CONSTRAINT ficha_inscripcion_id_cliente_0b9f36f7_fk_partner_id FOREIGN KEY (id_cliente) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ficha_inscripcion ficha_inscripcion_id_curso_6e014733_fk_curso_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.ficha_inscripcion
    ADD CONSTRAINT ficha_inscripcion_id_curso_6e014733_fk_curso_id FOREIGN KEY (id_curso) REFERENCES matricula.curso(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ficha_inscripcion ficha_inscripcion_id_empresa_53617669_fk_empresa_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.ficha_inscripcion
    ADD CONSTRAINT ficha_inscripcion_id_empresa_53617669_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ficha_inscripcion ficha_inscripcion_id_estudiante_2397b139_fk_partner_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.ficha_inscripcion
    ADD CONSTRAINT ficha_inscripcion_id_estudiante_2397b139_fk_partner_id FOREIGN KEY (id_estudiante) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ficha_inscripcion ficha_inscripcion_id_periodo_academico_36e67ba2_fk_periodo_a; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.ficha_inscripcion
    ADD CONSTRAINT ficha_inscripcion_id_periodo_academico_36e67ba2_fk_periodo_a FOREIGN KEY (id_periodo_academico) REFERENCES matricula.periodo_academico(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ficha_inscripcion ficha_inscripcion_id_representante_c15575d6_fk_partner_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.ficha_inscripcion
    ADD CONSTRAINT ficha_inscripcion_id_representante_c15575d6_fk_partner_id FOREIGN KEY (id_representante) REFERENCES core.partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ficha_inscripcion ficha_inscripcion_id_usuario_updated_bf5857b9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.ficha_inscripcion
    ADD CONSTRAINT ficha_inscripcion_id_usuario_updated_bf5857b9_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: periodo_academico periodo_academico_id_empresa_2d084f06_fk_empresa_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.periodo_academico
    ADD CONSTRAINT periodo_academico_id_empresa_2d084f06_fk_empresa_id FOREIGN KEY (id_empresa) REFERENCES core.empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: periodo_academico periodo_academico_id_usuario_updated_c5dfbe6f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: matricula; Owner: -
--

ALTER TABLE ONLY matricula.periodo_academico
    ADD CONSTRAINT periodo_academico_id_usuario_updated_c5dfbe6f_fk_auth_user_id FOREIGN KEY (id_usuario_updated) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict sdluDT2VsFNCuBsc1y0Q0dxCm4wWhxXG8vCgSRZtcVhEfaQuJs2GI0Q3mHP9rKY

