--
-- PostgreSQL database dump
--

\restrict FnfHwh9ezLLrJo3hMf4SdJe3J74wOyGJKpijyJKgosDY6g0RglLoFbFXaNOJG3f

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg12+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg12+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: finance_installment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.finance_installment (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    number integer NOT NULL,
    due_date date NOT NULL,
    amount numeric(10,2) NOT NULL,
    paid_amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    priority character varying(20) NOT NULL,
    payment_plan_id bigint NOT NULL,
    CONSTRAINT finance_installment_number_check CHECK ((number >= 0))
);


--
-- Name: finance_installment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.finance_installment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finance_installment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finance_payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.finance_payment (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    paid_at timestamp with time zone NOT NULL,
    amount numeric(10,2) NOT NULL,
    method character varying(20) NOT NULL,
    receipt_number character varying(60),
    proof character varying(100),
    notes text NOT NULL,
    installment_id bigint NOT NULL,
    registered_by_id bigint
);


--
-- Name: finance_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.finance_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finance_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finance_paymentplan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.finance_paymentplan (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    total_amount numeric(10,2) NOT NULL,
    discount_amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    notes text NOT NULL,
    enrollment_id bigint NOT NULL,
    generated_by_id bigint
);


--
-- Name: finance_paymentplan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.finance_paymentplan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finance_paymentplan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: people_enrollment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.people_enrollment (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    code character varying(40) NOT NULL,
    enrollment_date date NOT NULL,
    status character varying(20) NOT NULL,
    signed_document character varying(100),
    notes text NOT NULL,
    academic_period_id bigint NOT NULL,
    classroom_id bigint NOT NULL,
    institution_id bigint NOT NULL,
    student_id bigint NOT NULL
);


--
-- Name: people_enrollment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.people_enrollment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.people_enrollment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: people_representative; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.people_representative (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    document_type character varying(20) NOT NULL,
    document_number character varying(30) NOT NULL,
    first_names character varying(120) NOT NULL,
    last_names character varying(120) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(30) NOT NULL,
    secondary_phone character varying(30) NOT NULL,
    address text NOT NULL,
    institution_id bigint NOT NULL
);


--
-- Name: people_representative_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.people_representative ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.people_representative_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: people_student; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.people_student (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    document_type character varying(20) NOT NULL,
    document_number character varying(30) NOT NULL,
    first_names character varying(120) NOT NULL,
    last_names character varying(120) NOT NULL,
    birth_date date,
    gender character varying(30) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(30) NOT NULL,
    address text NOT NULL,
    status character varying(20) NOT NULL,
    institution_id bigint NOT NULL
);


--
-- Name: people_student_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.people_student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.people_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finance_installment finance_installment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_installment
    ADD CONSTRAINT finance_installment_pkey PRIMARY KEY (id);


--
-- Name: finance_payment finance_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_payment
    ADD CONSTRAINT finance_payment_pkey PRIMARY KEY (id);


--
-- Name: finance_payment finance_payment_receipt_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_payment
    ADD CONSTRAINT finance_payment_receipt_number_key UNIQUE (receipt_number);


--
-- Name: finance_paymentplan finance_paymentplan_enrollment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_paymentplan
    ADD CONSTRAINT finance_paymentplan_enrollment_id_key UNIQUE (enrollment_id);


--
-- Name: finance_paymentplan finance_paymentplan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_paymentplan
    ADD CONSTRAINT finance_paymentplan_pkey PRIMARY KEY (id);


--
-- Name: people_enrollment people_enrollment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people_enrollment
    ADD CONSTRAINT people_enrollment_pkey PRIMARY KEY (id);


--
-- Name: people_representative people_representative_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people_representative
    ADD CONSTRAINT people_representative_pkey PRIMARY KEY (id);


--
-- Name: people_student people_student_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people_student
    ADD CONSTRAINT people_student_pkey PRIMARY KEY (id);


--
-- Name: finance_installment uniq_installment_number_by_plan; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_installment
    ADD CONSTRAINT uniq_installment_number_by_plan UNIQUE (payment_plan_id, number);


--
-- Name: finance_installment_due_date_ea671c9c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_installment_due_date_ea671c9c ON public.finance_installment USING btree (due_date);


--
-- Name: finance_installment_is_deleted_ffdea8f4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_installment_is_deleted_ffdea8f4 ON public.finance_installment USING btree (is_deleted);


--
-- Name: finance_installment_payment_plan_id_6bf7f21d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_installment_payment_plan_id_6bf7f21d ON public.finance_installment USING btree (payment_plan_id);


--
-- Name: finance_installment_priority_4b07b4fc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_installment_priority_4b07b4fc ON public.finance_installment USING btree (priority);


--
-- Name: finance_installment_priority_4b07b4fc_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_installment_priority_4b07b4fc_like ON public.finance_installment USING btree (priority varchar_pattern_ops);


--
-- Name: finance_installment_status_cfff4936; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_installment_status_cfff4936 ON public.finance_installment USING btree (status);


--
-- Name: finance_installment_status_cfff4936_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_installment_status_cfff4936_like ON public.finance_installment USING btree (status varchar_pattern_ops);


--
-- Name: finance_payment_installment_id_1fbbc3ed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_payment_installment_id_1fbbc3ed ON public.finance_payment USING btree (installment_id);


--
-- Name: finance_payment_receipt_number_8badf46a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_payment_receipt_number_8badf46a_like ON public.finance_payment USING btree (receipt_number varchar_pattern_ops);


--
-- Name: finance_payment_registered_by_id_f15023fd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_payment_registered_by_id_f15023fd ON public.finance_payment USING btree (registered_by_id);


--
-- Name: finance_paymentplan_generated_by_id_eddae9ae; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_paymentplan_generated_by_id_eddae9ae ON public.finance_paymentplan USING btree (generated_by_id);


--
-- Name: finance_paymentplan_is_deleted_4fa1e5a4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_paymentplan_is_deleted_4fa1e5a4 ON public.finance_paymentplan USING btree (is_deleted);


--
-- Name: finance_paymentplan_status_b57169de; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_paymentplan_status_b57169de ON public.finance_paymentplan USING btree (status);


--
-- Name: finance_paymentplan_status_b57169de_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX finance_paymentplan_status_b57169de_like ON public.finance_paymentplan USING btree (status varchar_pattern_ops);


--
-- Name: people_enrollment_academic_period_id_b340cfd1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_enrollment_academic_period_id_b340cfd1 ON public.people_enrollment USING btree (academic_period_id);


--
-- Name: people_enrollment_classroom_id_3e771f44; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_enrollment_classroom_id_3e771f44 ON public.people_enrollment USING btree (classroom_id);


--
-- Name: people_enrollment_institution_id_d4edf2ac; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_enrollment_institution_id_d4edf2ac ON public.people_enrollment USING btree (institution_id);


--
-- Name: people_enrollment_is_deleted_f1ed6d5f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_enrollment_is_deleted_f1ed6d5f ON public.people_enrollment USING btree (is_deleted);


--
-- Name: people_enrollment_status_2140926b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_enrollment_status_2140926b ON public.people_enrollment USING btree (status);


--
-- Name: people_enrollment_status_2140926b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_enrollment_status_2140926b_like ON public.people_enrollment USING btree (status varchar_pattern_ops);


--
-- Name: people_enrollment_student_id_35a613d8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_enrollment_student_id_35a613d8 ON public.people_enrollment USING btree (student_id);


--
-- Name: people_representative_institution_id_4fba9ba8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_representative_institution_id_4fba9ba8 ON public.people_representative USING btree (institution_id);


--
-- Name: people_representative_is_deleted_f032724f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_representative_is_deleted_f032724f ON public.people_representative USING btree (is_deleted);


--
-- Name: people_student_institution_id_9e31ae03; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_student_institution_id_9e31ae03 ON public.people_student USING btree (institution_id);


--
-- Name: people_student_is_deleted_3d175726; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_student_is_deleted_3d175726 ON public.people_student USING btree (is_deleted);


--
-- Name: people_student_status_5a1e1ae6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_student_status_5a1e1ae6 ON public.people_student USING btree (status);


--
-- Name: people_student_status_5a1e1ae6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX people_student_status_5a1e1ae6_like ON public.people_student USING btree (status varchar_pattern_ops);


--
-- Name: uniq_active_enrollment_by_student_period; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_active_enrollment_by_student_period ON public.people_enrollment USING btree (student_id, academic_period_id) WHERE (NOT is_deleted);


--
-- Name: uniq_active_representative_document_by_institution; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_active_representative_document_by_institution ON public.people_representative USING btree (institution_id, document_number) WHERE (NOT is_deleted);


--
-- Name: uniq_active_student_document_by_institution; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_active_student_document_by_institution ON public.people_student USING btree (institution_id, document_number) WHERE (NOT is_deleted);


--
-- Name: finance_installment finance_installment_payment_plan_id_6bf7f21d_fk_finance_p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_installment
    ADD CONSTRAINT finance_installment_payment_plan_id_6bf7f21d_fk_finance_p FOREIGN KEY (payment_plan_id) REFERENCES public.finance_paymentplan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_payment finance_payment_installment_id_1fbbc3ed_fk_finance_i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_payment
    ADD CONSTRAINT finance_payment_installment_id_1fbbc3ed_fk_finance_i FOREIGN KEY (installment_id) REFERENCES public.finance_installment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_payment finance_payment_registered_by_id_f15023fd_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_payment
    ADD CONSTRAINT finance_payment_registered_by_id_f15023fd_fk_accounts_user_id FOREIGN KEY (registered_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_paymentplan finance_paymentplan_enrollment_id_9ef33c73_fk_people_en; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_paymentplan
    ADD CONSTRAINT finance_paymentplan_enrollment_id_9ef33c73_fk_people_en FOREIGN KEY (enrollment_id) REFERENCES public.people_enrollment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_paymentplan finance_paymentplan_generated_by_id_eddae9ae_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.finance_paymentplan
    ADD CONSTRAINT finance_paymentplan_generated_by_id_eddae9ae_fk_accounts_ FOREIGN KEY (generated_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: people_enrollment people_enrollment_academic_period_id_b340cfd1_fk_instituti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people_enrollment
    ADD CONSTRAINT people_enrollment_academic_period_id_b340cfd1_fk_instituti FOREIGN KEY (academic_period_id) REFERENCES public.institutions_academicperiod(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: people_enrollment people_enrollment_classroom_id_3e771f44_fk_instituti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people_enrollment
    ADD CONSTRAINT people_enrollment_classroom_id_3e771f44_fk_instituti FOREIGN KEY (classroom_id) REFERENCES public.institutions_classroom(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: people_enrollment people_enrollment_institution_id_d4edf2ac_fk_instituti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people_enrollment
    ADD CONSTRAINT people_enrollment_institution_id_d4edf2ac_fk_instituti FOREIGN KEY (institution_id) REFERENCES public.institutions_institution(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: people_enrollment people_enrollment_student_id_35a613d8_fk_people_student_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people_enrollment
    ADD CONSTRAINT people_enrollment_student_id_35a613d8_fk_people_student_id FOREIGN KEY (student_id) REFERENCES public.people_student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: people_representative people_representativ_institution_id_4fba9ba8_fk_instituti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people_representative
    ADD CONSTRAINT people_representativ_institution_id_4fba9ba8_fk_instituti FOREIGN KEY (institution_id) REFERENCES public.institutions_institution(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: people_student people_student_institution_id_9e31ae03_fk_instituti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people_student
    ADD CONSTRAINT people_student_institution_id_9e31ae03_fk_instituti FOREIGN KEY (institution_id) REFERENCES public.institutions_institution(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict FnfHwh9ezLLrJo3hMf4SdJe3J74wOyGJKpijyJKgosDY6g0RglLoFbFXaNOJG3f

