# Generated by Django 5.2.17 on 2026-08-20 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('matricula', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asignaturas_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."asignatura"',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='BancoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proceso', 'Proceso'), ('final', 'Simulador/final')], max_length=20)),
                ('meta_preguntas', models.IntegerField(default=10)),
                ('revisado_coordinacion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.asignatura')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bancos_pregunta_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."banco_pregunta"',
                'ordering': ['asignatura', 'tema', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.asignatura')),
                ('aula', models.ForeignKey(blank=True, db_column='id_aula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.aula')),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='docente_asignaturas', to='core.partner')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('periodo_academico', models.ForeignKey(db_column='id_periodo_academico', on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.periodoacademico')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='docente_asignaturas_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."docente_asignatura"',
                'ordering': ['periodo_academico', 'asignatura', 'docente'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_clase', models.IntegerField(default=1)),
                ('fecha_planificada', models.DateField()),
                ('objetivo', models.TextField()),
                ('actividades', models.TextField()),
                ('recursos_previstos', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revision'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='borrador', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('notas_revision', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.asignatura')),
                ('aula', models.ForeignKey(db_column='id_aula', on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.aula')),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='planificaciones_docente', to='core.partner')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('revisado_por', models.ForeignKey(blank=True, db_column='id_revisado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planificaciones_revisadas', to='core.partner')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planificaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."planificacion_clase"',
                'ordering': ['fecha_planificada', 'aula', 'numero_clase'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('respuestas', models.JSONField(blank=True, default=list)),
                ('respuesta_correcta', models.TextField(blank=True, null=True)),
                ('explicacion', models.TextField(blank=True, null=True)),
                ('dificultad', models.CharField(choices=[('facil', 'Facil'), ('media', 'Media'), ('dificil', 'Dificil')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revision'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('notas_revision', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('banco_pregunta', models.ForeignKey(db_column='id_banco_pregunta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='preguntas', to='academico.bancopregunta')),
                ('creado_por', models.ForeignKey(db_column='id_creado_por', on_delete=django.db.models.deletion.DO_NOTHING, related_name='preguntas_creadas', to='core.partner')),
                ('revisado_por', models.ForeignKey(blank=True, db_column='id_revisado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preguntas_revisadas', to='core.partner')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preguntas_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."pregunta"',
                'ordering': ['banco_pregunta', '-created'],
            },
        ),
        migrations.CreateModel(
            name='RecursoClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('video', 'Video'), ('enlace', 'Enlace'), ('diapositiva', 'Diapositiva'), ('otro', 'Otro')], default='documento', max_length=20)),
                ('url', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='academico/recursos/')),
                ('listo', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='id_creado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.partner')),
                ('planificacion_clase', models.ForeignKey(db_column='id_planificacion_clase', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recursos', to='academico.planificacionclase')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recursos_clase_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."recurso_clase"',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('orden', models.IntegerField(default=1)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subtemas_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."subtema"',
                'ordering': ['tema', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='planificacionclase',
            name='subtema',
            field=models.ForeignKey(blank=True, db_column='id_subtema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.subtema'),
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='subtema',
            field=models.ForeignKey(blank=True, db_column='id_subtema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.subtema'),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('orden', models.IntegerField(default=1)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('numero_clases', models.IntegerField(default=1)),
                ('dificultad', models.CharField(choices=[('basica', 'Basica'), ('media', 'Media'), ('avanzada', 'Avanzada')], default='media', max_length=20)),
                ('meta_preguntas_proceso', models.IntegerField(default=10)),
                ('meta_preguntas_final', models.IntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temas_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."tema"',
                'ordering': ['temario', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='subtema',
            name='tema',
            field=models.ForeignKey(db_column='id_tema', on_delete=django.db.models.deletion.DO_NOTHING, related_name='subtemas', to='academico.tema'),
        ),
        migrations.AddField(
            model_name='planificacionclase',
            name='tema',
            field=models.ForeignKey(db_column='id_tema', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.tema'),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('proceso', 'Proceso'), ('final', 'Final'), ('simulador', 'Simulador')], default='proceso', max_length=20)),
                ('fecha', models.DateField()),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.asignatura')),
                ('creado_por', models.ForeignKey(blank=True, db_column='id_creado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.partner')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('planificacion_clase', models.ForeignKey(blank=True, db_column='id_planificacion_clase', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.planificacionclase')),
                ('tema', models.ForeignKey(blank=True, db_column='id_tema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.tema')),
            ],
            options={
                'db_table': '"academico"."evaluacion"',
                'ordering': ['-fecha', 'asignatura'],
            },
        ),
        migrations.AddField(
            model_name='bancopregunta',
            name='tema',
            field=models.ForeignKey(blank=True, db_column='id_tema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.tema'),
        ),
        migrations.CreateModel(
            name='Temario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, related_name='temarios', to='academico.asignatura')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('periodo_academico', models.ForeignKey(blank=True, db_column='id_periodo_academico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.periodoacademico')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temarios_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."temario"',
                'ordering': ['asignatura', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='tema',
            name='temario',
            field=models.ForeignKey(db_column='id_temario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='temas', to='academico.temario'),
        ),
        migrations.CreateModel(
            name='EvaluacionResultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluacion_resultados', to='core.partner')),
                ('evaluacion', models.ForeignKey(db_column='id_evaluacion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='resultados', to='academico.evaluacion')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluacion_resultados_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."evaluacion_resultado"',
                'ordering': ['evaluacion', 'estudiante'],
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('atraso', 'Atraso'), ('justificado', 'Justificado')], max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, related_name='asistencias', to='core.partner')),
                ('registrado_por', models.ForeignKey(blank=True, db_column='id_registrado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.partner')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asistencias_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('planificacion_clase', models.ForeignKey(db_column='id_planificacion_clase', on_delete=django.db.models.deletion.DO_NOTHING, related_name='asistencias', to='academico.planificacionclase')),
            ],
            options={
                'db_table': '"academico"."asistencia"',
                'ordering': ['planificacion_clase', 'estudiante'],
                'unique_together': {('planificacion_clase', 'estudiante')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='subtema',
            unique_together={('tema', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('temario', 'orden')},
        ),
    ]
