# Generated by Django 5.2.17 on 2026-08-22 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('core', '0002_vistas'),
        ('matricula', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_planificacion', models.CharField(blank=True, max_length=120, null=True)),
                ('tema_previsto', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('no_dio_clases', 'No dio clases'), ('reprogramada', 'Reprogramada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, related_name='horarios_clase', to='academico.asignatura')),
                ('aula', models.ForeignKey(db_column='id_aula', on_delete=django.db.models.deletion.DO_NOTHING, related_name='horarios_clase', to='matricula.aula')),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='horarios_docente', to='core.partner')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('periodo_academico', models.ForeignKey(db_column='id_periodo_academico', on_delete=django.db.models.deletion.DO_NOTHING, related_name='horarios_clase', to='matricula.periodoacademico')),
                ('tutor', models.ForeignKey(blank=True, db_column='id_tutor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='horarios_tutor', to='core.partner')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='horarios_clase_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."horario_clase"',
                'ordering': ['fecha', 'hora_inicio', 'aula', 'asignatura'],
                'unique_together': {('periodo_academico', 'aula', 'fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
