# Generated by Django 5.2.17 on 2026-08-22 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_horarioclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionclase',
            name='competencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planificacionclase',
            name='estrategias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planificacionclase',
            name='horario_clase',
            field=models.OneToOneField(blank=True, db_column='id_horario_clase', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planificacion', to='academico.horarioclase'),
        ),
        migrations.AlterField(
            model_name='planificacionclase',
            name='actividades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planificacionclase',
            name='objetivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planificacionclase',
            name='tema',
            field=models.ForeignKey(blank=True, db_column='id_tema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.tema'),
        ),
    ]
