# Generated by Django 5.2.17 on 2026-08-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_planificacionclase_competencias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioclase',
            name='tipo_planificacion',
        ),
    ]
