# Generated by Django 5.2.17 on 2026-08-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_remove_horarioclase_tipo_planificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionclase',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'En revision'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
