# Generated by Django 5.2.17 on 2026-08-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_planificacionclase_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacionclase',
            options={'ordering': ['fecha_planificada', 'aula', 'numero_clase'], 'permissions': (('review_planificacionclase', 'Puede revisar planificaciones de clase'),)},
        ),
    ]
