# Generated by Django 5.2.17 on 2026-08-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_planificacionclase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioclase',
            options={'ordering': ['fecha', 'hora_inicio', 'aula', 'asignatura'], 'permissions': (('view_all_horarioclase', 'Puede ver todos los horarios'),)},
        ),
    ]
