# Generated by Django 5.2.17 on 2026-08-25 06:46

import django.db.models.deletion
from django.db import migrations, models


DROP_INDICADOR_VIEW_SQL = "DROP VIEW IF EXISTS academico.v_indicador_preguntas_docente;"

CREATE_INDICADOR_VIEW_SQL = """
CREATE OR REPLACE VIEW academico.v_indicador_preguntas_docente AS
SELECT
    bp.id_empresa,
    p.id_creado_por AS id_docente,
    docente.nombre AS docente,
    a.nombre AS asignatura,
    t.nombre AS tema,
    bp.tipo,
    bp.meta_preguntas,
    count(p.id) AS preguntas_creadas,
    (bp.meta_preguntas - count(p.id)) AS preguntas_pendientes
FROM academico.banco_pregunta bp
JOIN academico.asignatura a ON a.id = bp.id_asignatura
LEFT JOIN academico.tema t ON t.id = bp.id_tema
LEFT JOIN academico.pregunta p ON p.id_banco_pregunta = bp.id AND p.activo = true
LEFT JOIN core.partner docente ON docente.id = p.id_creado_por
WHERE bp.activo = true
GROUP BY bp.id_empresa, p.id_creado_por, docente.nombre, a.nombre, t.nombre, bp.tipo, bp.meta_preguntas;
"""


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('academico', '0019_estado_profesor_materia_curso'),
    ]

    operations = [
        migrations.RunSQL(
            sql=DROP_INDICADOR_VIEW_SQL,
            reverse_sql=CREATE_INDICADOR_VIEW_SQL,
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"academico"."competencia"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"academico"."estrategia"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"academico"."recurso"',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='subtema',
            options={'ordering': ['tema', 'orden', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['planificacion', 'orden', 'nombre']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='subtema',
                    unique_together=set(),
                ),
                migrations.AlterUniqueTogether(
                    name='tema',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddField(
            model_name='subtema',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtema',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subtema',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subtema',
            name='tema',
            field=models.ForeignKey(db_column='id_tema', on_delete=django.db.models.deletion.CASCADE, related_name='subtemas_planificacion', to='academico.tema'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PlanificacionDocente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_materia_curso', models.ForeignKey(db_column='id_profesor_materia_curso', on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='academico.profesormateriacurso')),
            ],
            options={
                'db_table': '"academico"."planificacion"',
                'ordering': ['profesor_materia_curso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClasePlanificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=1)),
                ('planificacion', models.ForeignKey(db_column='id_planificacion', on_delete=django.db.models.deletion.CASCADE, related_name='clases_planificacion', to='academico.planificaciondocente')),
            ],
            options={
                'db_table': '"academico"."clase_planificacion"',
                'ordering': ['planificacion', 'orden', 'numero'],
                'unique_together': {('planificacion', 'numero')},
            },
        ),
        migrations.RunSQL(
            sql="""
                UPDATE academico.planificacion_clase
                SET id_tema = NULL,
                    id_subtema = NULL;

                UPDATE academico.banco_pregunta
                SET id_tema = NULL,
                    id_subtema = NULL;

                UPDATE academico.evaluacion
                SET id_tema = NULL;

                DELETE FROM academico.subtema;
                DELETE FROM academico.tema;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='tema',
            name='planificacion',
            field=models.ForeignKey(db_column='id_planificacion', on_delete=django.db.models.deletion.CASCADE, related_name='temas_planificacion', to='academico.planificaciondocente'),
        ),
        migrations.RemoveField(
            model_name='subtema',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='subtema',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subtema',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='subtema',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='subtema',
            name='usuario_updated',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='meta_preguntas_final',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='meta_preguntas_proceso',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='numero_clases',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='temario',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='usuario_updated',
        ),
        migrations.CreateModel(
            name='ClaseEstrategia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField(default=1)),
                ('clase_planificacion', models.ForeignKey(db_column='id_clase_planificacion', on_delete=django.db.models.deletion.CASCADE, related_name='estrategias_clase', to='academico.claseplanificacion')),
                ('estrategia', models.ForeignKey(db_column='id_estrategia', on_delete=django.db.models.deletion.RESTRICT, related_name='clases_estrategia', to='academico.estrategia')),
            ],
            options={
                'db_table': '"academico"."clase_estrategia"',
                'ordering': ['clase_planificacion', 'orden', 'estrategia'],
                'unique_together': {('clase_planificacion', 'estrategia')},
            },
        ),
        migrations.CreateModel(
            name='PlanificacionCompetencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('competencia', models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.RESTRICT, related_name='planificaciones_competencia', to='academico.competencia')),
                ('planificacion', models.ForeignKey(db_column='id_planificacion', on_delete=django.db.models.deletion.CASCADE, related_name='competencias_planificacion', to='academico.planificaciondocente')),
            ],
            options={
                'db_table': '"academico"."planificacion_competencia"',
                'ordering': ['planificacion', 'competencia'],
                'unique_together': {('planificacion', 'competencia')},
            },
        ),
        migrations.CreateModel(
            name='PlanificacionRecurso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('planificacion', models.ForeignKey(db_column='id_planificacion', on_delete=django.db.models.deletion.CASCADE, related_name='recursos_planificacion', to='academico.planificaciondocente')),
                ('recurso', models.ForeignKey(db_column='id_recurso', on_delete=django.db.models.deletion.RESTRICT, related_name='planificaciones_recurso', to='academico.recurso')),
            ],
            options={
                'db_table': '"academico"."planificacion_recurso"',
                'ordering': ['planificacion', 'recurso'],
                'unique_together': {('planificacion', 'recurso')},
            },
        ),
        migrations.RunSQL(
            sql=CREATE_INDICADOR_VIEW_SQL,
            reverse_sql=DROP_INDICADOR_VIEW_SQL,
        ),
    ]
