# Generated by Django 5.2.17 on 2026-08-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0020_reemplazar_temas_por_planificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificaciondocente',
            options={'ordering': ['materia_curso', 'nombre']},
        ),
        migrations.AddField(
            model_name='planificaciondocente',
            name='materia_curso',
            field=models.ForeignKey(blank=True, db_column='id_materia_curso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='academico.materiacurso'),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE academico.planificacion p
                SET id_materia_curso = pmc.id_materia_curso
                FROM academico.profesor_materia_curso pmc
                WHERE pmc.id = p.id_profesor_materia_curso;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='planificaciondocente',
            name='materia_curso',
            field=models.ForeignKey(db_column='id_materia_curso', on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='academico.materiacurso'),
        ),
        migrations.RemoveField(
            model_name='planificaciondocente',
            name='profesor_materia_curso',
        ),
    ]
