# Generated by Django 5.2.17 on 2026-08-25 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0021_planificacion_por_materia_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='numero_clase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='subtema',
            field=models.ForeignKey(blank=True, db_column='id_subtema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='academico.subtema'),
        ),
        migrations.AddField(
            model_name='clase',
            name='tema',
            field=models.ForeignKey(blank=True, db_column='id_tema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='academico.tema'),
        ),
    ]
