# Generated by Django 5.2.17 on 2026-08-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0022_clase_tema_subtema_planificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='numero_clase',
        ),
        migrations.AddField(
            model_name='clase',
            name='competencias',
            field=models.ManyToManyField(blank=True, related_name='clases', to='academico.competencia'),
        ),
        migrations.AddField(
            model_name='clase',
            name='estrategias',
            field=models.ManyToManyField(blank=True, related_name='clases', to='academico.estrategia'),
        ),
        migrations.AddField(
            model_name='clase',
            name='recursos',
            field=models.ManyToManyField(blank=True, related_name='clases', to='academico.recurso'),
        ),
    ]
