# Generated by Django 5.2.17 on 2026-08-25 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0023_clase_etiquetas_planificacion'),
        ('core', '0004_partner_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estado_planificacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'En revision'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='notas_revision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='revisado_por',
            field=models.ForeignKey(blank=True, db_column='id_revisado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_revisadas', to='core.partner'),
        ),
    ]
