# Generated by Django 5.2.17 on 2026-08-25 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0024_clase_revision_planificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='revision_competencias_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='revision_detalle_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='revision_estrategias_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='revision_recursos_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='revision_tema_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClaseRecurso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='academico/clase_recursos/')),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, related_name='clase_recursos', to='academico.clase')),
                ('recurso', models.ForeignKey(db_column='id_recurso', on_delete=django.db.models.deletion.CASCADE, related_name='clase_recursos', to='academico.recurso')),
            ],
            options={
                'db_table': '"academico"."clase_recurso"',
                'ordering': ['clase', 'recurso'],
                'unique_together': {('clase', 'recurso')},
            },
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO academico.clase_recurso (id_clase, id_recurso)
                SELECT clase_id, recurso_id
                FROM academico.clase_recursos
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM academico.clase_recurso cr
                    WHERE cr.id_clase = academico.clase_recursos.clase_id
                      AND cr.id_recurso = academico.clase_recursos.recurso_id
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='clase',
                    name='recursos',
                    field=models.ManyToManyField(blank=True, related_name='clases', through='academico.ClaseRecurso', to='academico.recurso'),
                ),
            ],
        ),
    ]
