# Generated by Django 5.2.17 on 2026-08-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0025_clase_recurso_archivo_revision_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='observaciones_revision',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
