# Generated by Django 5.2.17 on 2026-08-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0026_clase_observaciones_revision'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE academico.horario_aula_curso
                    DROP CONSTRAINT IF EXISTS uq_horario_aula_curso;

                    ALTER TABLE academico.horario_aula_curso
                    ADD COLUMN IF NOT EXISTS fecha DATE;

                    CREATE UNIQUE INDEX IF NOT EXISTS uq_horario_aula_curso_periodo
                    ON academico.horario_aula_curso (id_aula_curso, id_horario_dia)
                    WHERE fecha IS NULL;

                    CREATE UNIQUE INDEX IF NOT EXISTS uq_horario_aula_curso_fecha
                    ON academico.horario_aula_curso (id_aula_curso, id_horario_dia, fecha)
                    WHERE fecha IS NOT NULL;
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS academico.uq_horario_aula_curso_fecha;
                    DROP INDEX IF EXISTS academico.uq_horario_aula_curso_periodo;

                    ALTER TABLE academico.horario_aula_curso
                    DROP COLUMN IF EXISTS fecha;

                    ALTER TABLE academico.horario_aula_curso
                    ADD CONSTRAINT uq_horario_aula_curso
                    UNIQUE (id_aula_curso, id_horario_dia);
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterModelOptions(
                    name="horarioaulacurso",
                    options={"ordering": ["aula_curso", "horario_dia", "fecha"]},
                ),
                migrations.AlterUniqueTogether(
                    name="horarioaulacurso",
                    unique_together=set(),
                ),
                migrations.AddField(
                    model_name="horarioaulacurso",
                    name="fecha",
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddConstraint(
                    model_name="horarioaulacurso",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("fecha__isnull", True)),
                        fields=("aula_curso", "horario_dia"),
                        name="uq_horario_aula_curso_periodo",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="horarioaulacurso",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("fecha__isnull", False)),
                        fields=("aula_curso", "horario_dia", "fecha"),
                        name="uq_horario_aula_curso_fecha",
                    ),
                ),
            ],
        ),
    ]
