# Generated by Django 5.2.17 on 2026-08-28 04:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0027_alter_horarioaulacurso_options_and_more'),
        ('core', '0004_partner_foto'),
        ('matricula', '0004_rename_pago_unico_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEstudiante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado')], default='activo', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.RESTRICT, related_name='grupo_asignaciones', to='core.partner')),
                ('ficha_inscripcion', models.OneToOneField(db_column='id_ficha_inscripcion', on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_grupo', to='matricula.fichainscripcion')),
                ('grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_asignados', to='academico.curso')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grupo_estudiantes_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."grupo_estudiante"',
                'ordering': ['grupo', 'estudiante__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClaseAsistencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('atraso', 'Atraso'), ('justificado', 'Justificado')], default='presente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_clase', to='academico.clase')),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.RESTRICT, related_name='asistencias_clase', to='core.partner')),
                ('registrado_por', models.ForeignKey(blank=True, db_column='id_registrado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asistencias_clase_registradas', to='core.partner')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asistencias_clase_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."clase_asistencia"',
                'ordering': ['clase', 'estudiante__nombre'],
                'unique_together': {('clase', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='ClaseEstudianteMovimiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clase_destino', models.ForeignKey(db_column='id_clase_destino', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='academico.clase')),
                ('clase_origen', models.ForeignKey(db_column='id_clase_origen', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='academico.clase')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimientos_clase_actualizados', to=settings.AUTH_USER_MODEL)),
                ('asignacion', models.ForeignKey(db_column='id_grupo_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_clase', to='academico.grupoestudiante')),
            ],
            options={
                'db_table': '"academico"."clase_estudiante_movimiento"',
                'ordering': ['-created_at'],
                'unique_together': {('asignacion', 'clase_origen')},
            },
        ),
    ]
