# Generated by Django 5.2.17 on 2026-08-28 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0028_grupoestudiante_claseasistencia_and_more'),
        ('core', '0004_partner_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='asistencia_cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='asistencia_cerrada_por',
            field=models.ForeignKey(blank=True, db_column='id_asistencia_cerrada_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_asistencia_cerradas', to='core.partner'),
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha_cierre_asistencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
