# Generated by Codex on 2026-08-28

from django.db import migrations, models
from django.utils import timezone


def fill_fecha_inicio(apps, schema_editor):
    ClaseEstudianteMovimiento = apps.get_model("academico", "ClaseEstudianteMovimiento")
    for movimiento in ClaseEstudianteMovimiento.objects.select_related("clase_origen").filter(fecha_inicio__isnull=True):
        movimiento.fecha_inicio = movimiento.clase_origen.fecha
        movimiento.save(update_fields=["fecha_inicio"])


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0029_clase_asistencia_cerrada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claseestudiantemovimiento",
            name="fecha_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(fill_fecha_inicio, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="claseestudiantemovimiento",
            name="fecha_inicio",
            field=models.DateField(default=timezone.localdate),
        ),
    ]
