# Generated by Codex on 2026-08-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_partner_foto"),
        ("academico", "0030_claseestudiantemovimiento_fecha_inicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="clase",
            name="docente",
            field=models.ForeignKey(
                blank=True,
                db_column="id_docente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clases_asignadas",
                to="core.partner",
            ),
        ),
    ]
