# Generated by Codex on 2026-08-30

from django.db import migrations, models


def preserve_existing_docente_overrides(apps, schema_editor):
    Clase = apps.get_model("academico", "Clase")
    Clase.objects.filter(docente__isnull=False).update(docente_override=True)


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0031_clase_docente"),
    ]

    operations = [
        migrations.AddField(
            model_name="clase",
            name="docente_override",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_existing_docente_overrides, migrations.RunPython.noop),
    ]
