# Generated by Django 5.2.17 on 2026-09-01 03:28

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_subtopics(apps, schema_editor):
    Clase = apps.get_model("academico", "Clase")
    ClaseSubtema = apps.get_model("academico", "ClaseSubtema")
    for clase in Clase.objects.exclude(subtema_id__isnull=True).iterator():
        ClaseSubtema.objects.get_or_create(
            clase_id=clase.pk,
            subtema_id=clase.subtema_id,
            defaults={"orden": 1},
        )


def remove_copied_subtopics(apps, schema_editor):
    ClaseSubtema = apps.get_model("academico", "ClaseSubtema")
    ClaseSubtema.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0032_clase_docente_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseSubtema',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField(default=1)),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, related_name='clase_subtemas', to='academico.clase')),
                ('subtema', models.ForeignKey(db_column='id_subtema', on_delete=django.db.models.deletion.CASCADE, related_name='clase_subtemas', to='academico.subtema')),
            ],
            options={
                'db_table': '"academico"."clase_subtema"',
                'ordering': ['clase', 'orden', 'subtema'],
                'unique_together': {('clase', 'subtema')},
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='subtemas',
            field=models.ManyToManyField(blank=True, related_name='clases_asignadas', through='academico.ClaseSubtema', to='academico.subtema'),
        ),
        migrations.RunPython(copy_existing_subtopics, remove_copied_subtopics),
    ]
