# Generated by Django 5.2.17 on 2026-09-01 03:35

import django.db.models.deletion
from django.db import migrations, models


def create_existing_planificaciones_tema(apps, schema_editor):
    ProfesorMateriaCurso = apps.get_model("academico", "ProfesorMateriaCurso")
    Tema = apps.get_model("academico", "Tema")
    PlanificacionTema = apps.get_model("academico", "PlanificacionTema")

    profesores_materia = ProfesorMateriaCurso.objects.select_related(
        "materia_curso__grupo",
        "materia_curso__materia",
    )
    for profesor_materia_curso in profesores_materia.iterator():
        materia_curso = profesor_materia_curso.materia_curso
        temas = Tema.objects.filter(
            planificacion__materia_curso_id=materia_curso.pk,
        ).order_by("orden", "nombre")
        for tema in temas:
            nombre = f"{materia_curso.grupo.nombre} - {materia_curso.materia.nombre} - {tema.nombre}"
            PlanificacionTema.objects.get_or_create(
                profesor_materia_curso_id=profesor_materia_curso.pk,
                tema_id=tema.pk,
                defaults={"nombre": nombre},
            )


def remove_existing_planificaciones_tema(apps, schema_editor):
    PlanificacionTema = apps.get_model("academico", "PlanificacionTema")
    PlanificacionTema.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0033_clasesubtema_clase_subtemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionTema',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=220)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor_materia_curso', models.ForeignKey(db_column='id_profesor_materia_curso', on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones_tema', to='academico.profesormateriacurso')),
                ('tema', models.ForeignKey(db_column='id_tema', on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones_tema', to='academico.tema')),
            ],
            options={
                'db_table': '"academico"."planificacion_tema"',
                'ordering': ['profesor_materia_curso', 'tema__orden', 'tema__nombre'],
                'unique_together': {('profesor_materia_curso', 'tema')},
            },
        ),
        migrations.RunPython(create_existing_planificaciones_tema, remove_existing_planificaciones_tema),
    ]
