# Generated by Django 5.2.17 on 2026-09-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0034_planificaciontema"),
    ]

    operations = [
        migrations.CreateModel(
            name="MateriaTema",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("detalle", models.TextField(blank=True, null=True)),
                ("orden", models.IntegerField(default=1)),
                (
                    "materia",
                    models.ForeignKey(
                        db_column="id_materia",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temas_base",
                        to="academico.materia",
                    ),
                ),
            ],
            options={
                "db_table": '"academico"."materia_tema"',
                "ordering": ["materia", "orden", "nombre"],
                "unique_together": {("materia", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="MateriaSubtema",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("orden", models.IntegerField(default=1)),
                (
                    "tema",
                    models.ForeignKey(
                        db_column="id_materia_tema",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtemas_base",
                        to="academico.materiatema",
                    ),
                ),
            ],
            options={
                "db_table": '"academico"."materia_subtema"',
                "ordering": ["tema", "orden", "nombre"],
                "unique_together": {("tema", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="tema",
            name="materia_tema",
            field=models.ForeignKey(
                blank=True,
                db_column="id_materia_tema",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temas_generados",
                to="academico.materiatema",
            ),
        ),
        migrations.AddField(
            model_name="subtema",
            name="materia_subtema",
            field=models.ForeignKey(
                blank=True,
                db_column="id_materia_subtema",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtemas_generados",
                to="academico.materiasubtema",
            ),
        ),
    ]
