# Generated by Django 5.2.17 on 2026-09-01 00:05

from django.db import migrations


def backfill_materia_temas(apps, schema_editor):
    PlanificacionDocente = apps.get_model("academico", "PlanificacionDocente")
    MateriaTema = apps.get_model("academico", "MateriaTema")
    MateriaSubtema = apps.get_model("academico", "MateriaSubtema")

    planificaciones = PlanificacionDocente.objects.select_related("materia_curso__materia")
    for planificacion in planificaciones.iterator():
        materia_id = planificacion.materia_curso.materia_id
        temas = planificacion.temas_planificacion.prefetch_related("subtemas_planificacion").order_by("orden", "nombre")
        for tema in temas:
            materia_tema = (
                MateriaTema.objects.filter(materia_id=materia_id, nombre__iexact=tema.nombre)
                .order_by("id")
                .first()
            )
            if materia_tema is None:
                materia_tema = MateriaTema.objects.create(
                    materia_id=materia_id,
                    nombre=tema.nombre,
                    detalle=tema.detalle,
                    orden=tema.orden,
                )
            elif not materia_tema.detalle and tema.detalle:
                materia_tema.detalle = tema.detalle
                materia_tema.save(update_fields=["detalle"])

            if tema.materia_tema_id != materia_tema.pk:
                tema.materia_tema_id = materia_tema.pk
                tema.save(update_fields=["materia_tema"])

            for subtema in tema.subtemas_planificacion.order_by("orden", "nombre"):
                materia_subtema = (
                    MateriaSubtema.objects.filter(tema=materia_tema, nombre__iexact=subtema.nombre)
                    .order_by("id")
                    .first()
                )
                if materia_subtema is None:
                    materia_subtema = MateriaSubtema.objects.create(
                        tema=materia_tema,
                        nombre=subtema.nombre,
                        descripcion=subtema.descripcion,
                        orden=subtema.orden,
                    )
                elif not materia_subtema.descripcion and subtema.descripcion:
                    materia_subtema.descripcion = subtema.descripcion
                    materia_subtema.save(update_fields=["descripcion"])

                if subtema.materia_subtema_id != materia_subtema.pk:
                    subtema.materia_subtema_id = materia_subtema.pk
                    subtema.save(update_fields=["materia_subtema"])


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0035_materiatema_materiasubtema_tema_materia_sources"),
    ]

    operations = [
        migrations.RunPython(backfill_materia_temas, migrations.RunPython.noop),
    ]
