# Generated by Django 5.2.17 on 2026-09-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0036_backfill_materia_temas"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesormateriacurso",
            name="auto_generada_por_clases",
            field=models.BooleanField(default=False),
        ),
    ]
