# Generated by Django 5.2.17 on 2026-09-04 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0037_profesormateriacurso_auto_generada_por_clases'),
        ('core', '0008_partner_full_name_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseHoraDocente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asistio', 'Asistio'), ('reemplazo', 'Reemplazo'), ('no_asistio', 'No asistio'), ('suspendida', 'Suspendida')], default='pendiente', max_length=20)),
                ('horas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clase', models.OneToOneField(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, related_name='hora_docente', to='academico.clase')),
                ('docente', models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_docente', to='core.partner')),
                ('docente_reemplazado', models.ForeignKey(blank=True, db_column='id_docente_reemplazado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_docente_reemplazadas', to='core.partner')),
                ('registrado_por', models.ForeignKey(blank=True, db_column='id_registrado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='horas_docente_registradas', to=settings.AUTH_USER_MODEL)),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='horas_docente_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"academico"."clase_hora_docente"',
                'ordering': ['clase'],
                'permissions': (('report_clasehoradocente', 'Puede ver reporte de horas docente'),),
            },
        ),
    ]
