# Generated by Django 5.2.17 on 2026-09-05 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0038_clasehoradocente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiatema',
            options={'ordering': ['materia', 'orden', 'nombre'], 'permissions': (('restrict_to_assigned_materiatema', 'Ver y gestionar solo temas de materias asignadas'),)},
        ),
    ]
