# Generated by Django 5.2.17 on 2026-09-05 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0039_materia_temas_asignados'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sitio', models.URLField(blank=True)),
                ('curso_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('materia_curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aula_moodle', to='academico.materiacurso')),
            ],
            options={
                'db_table': '"academico"."moodle_curso"',
                'permissions': (('crear_moodlecurso', 'Crear curso en Moodle con docentes y alumnos'),),
                'default_permissions': (),
            },
        ),
    ]
