# Generated by Django 5.2.17 on 2026-09-05 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0040_moodlecurso'),
        ('core', '0008_partner_full_name_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio', models.URLField()),
                ('clave', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usuario', models.CharField(max_length=100)),
                ('usuario_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('clave_inicial_cifrada', models.TextField(blank=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_moodle', to='core.partner')),
            ],
            options={
                'db_table': '"academico"."moodle_cuenta"',
                'permissions': (('exportar_moodlecuenta', 'Descargar Excel de accesos iniciales Moodle'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MoodleMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('confirmada', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.moodlecuenta')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.moodlecurso')),
            ],
            options={
                'db_table': '"academico"."moodle_matricula"',
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='moodlecuenta',
            constraint=models.UniqueConstraint(fields=('persona', 'sitio'), name='moodle_cuenta_persona_sitio'),
        ),
        migrations.AddConstraint(
            model_name='moodlecuenta',
            constraint=models.UniqueConstraint(fields=('usuario', 'sitio'), name='moodle_cuenta_usuario_sitio'),
        ),
        migrations.AddConstraint(
            model_name='moodlematricula',
            constraint=models.UniqueConstraint(fields=('curso', 'cuenta'), name='moodle_matricula_curso_cuenta'),
        ),
    ]
