# Generated by Django 5.2.17 on 2026-09-07 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0041_moodlecuenta_moodlematricula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleConfiguracion',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('base_url', models.CharField(default='https://aula.solucionesintegrales.xyz', max_length=500, verbose_name='URL de Moodle')),
                ('token_cifrado', models.TextField(blank=True, editable=False)),
                ('ultima_prueba', models.DateTimeField(blank=True, null=True)),
                ('ultima_prueba_exitosa', models.BooleanField(blank=True, null=True)),
                ('ultimo_resultado', models.CharField(blank=True, max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuración de Moodle',
                'verbose_name_plural': 'configuración de Moodle',
                'db_table': '"academico"."moodle_configuracion"',
                'default_permissions': (),
            },
        ),
    ]
