# Generated by Django 5.2.17 on 2026-09-09 21:11

from django.db import migrations, models


def associate_catalogs_with_materias(apps, schema_editor):
    database = schema_editor.connection.alias
    Clase = apps.get_model("academico", "Clase")
    ClaseEstrategia = apps.get_model("academico", "ClaseEstrategia")
    ClaseRecurso = apps.get_model("academico", "ClaseRecurso")
    Competencia = apps.get_model("academico", "Competencia")
    Estrategia = apps.get_model("academico", "Estrategia")
    PlanificacionCompetencia = apps.get_model("academico", "PlanificacionCompetencia")
    PlanificacionRecurso = apps.get_model("academico", "PlanificacionRecurso")
    Recurso = apps.get_model("academico", "Recurso")

    def insert_pairs(model, tag_field, pair_sources):
        pairs = set()
        for source in pair_sources:
            pairs.update((tag_id, materia_id) for tag_id, materia_id in source if tag_id and materia_id)
        through = model.materias.through
        through.objects.using(database).bulk_create(
            [
                through(**{f"{tag_field}_id": tag_id, "materia_id": materia_id})
                for tag_id, materia_id in pairs
            ],
            ignore_conflicts=True,
        )

    insert_pairs(
        Competencia,
        "competencia",
        (
            Clase.competencias.through.objects.using(database).values_list(
                "competencia_id", "clase__materia_curso__materia_id"
            ),
            PlanificacionCompetencia.objects.using(database).values_list(
                "competencia_id", "planificacion__materia_curso__materia_id"
            ),
        ),
    )
    insert_pairs(
        Estrategia,
        "estrategia",
        (
            Clase.estrategias.through.objects.using(database).values_list(
                "estrategia_id", "clase__materia_curso__materia_id"
            ),
            ClaseEstrategia.objects.using(database).values_list(
                "estrategia_id", "clase_planificacion__planificacion__materia_curso__materia_id"
            ),
        ),
    )
    insert_pairs(
        Recurso,
        "recurso",
        (
            ClaseRecurso.objects.using(database).values_list(
                "recurso_id", "clase__materia_curso__materia_id"
            ),
            PlanificacionRecurso.objects.using(database).values_list(
                "recurso_id", "planificacion__materia_curso__materia_id"
            ),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0043_moodleconfiguracion_clave_inicial_cifrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='competencias_catalogo', to='academico.materia'),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='estrategias_catalogo', to='academico.materia'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='recursos_catalogo', to='academico.materia'),
        ),
        migrations.RunPython(associate_catalogs_with_materias, migrations.RunPython.noop),
    ]
