# Generated by Django 5.2.17 on 2026-09-13 06:09

import apps.academico.models
import apps.academico.storage
import os
import uuid

from django.conf import settings
from django.core.files import File
from django.core.files.storage import FileSystemStorage
from django.db import migrations, models
from django.db import transaction
from django.utils._os import safe_join

from apps.academico.storage import BolsaRecursosStorage


def move_resource_files(apps, schema_editor, reverse=False):
    ClaseRecurso = apps.get_model("academico", "ClaseRecurso")
    source_prefix = "academico/bolsa_recursos/" if reverse else "academico/clase_recursos/"
    source_root = settings.PRIVATE_MEDIA_ROOT if reverse else settings.MEDIA_ROOT
    target_storage = (
        FileSystemStorage(location=settings.MEDIA_ROOT)
        if reverse else BolsaRecursosStorage()
    )
    pending_delete = set()
    recursos = (
        ClaseRecurso.objects.using(schema_editor.connection.alias)
        .filter(archivo__startswith=source_prefix)
        .select_related("clase__materia_curso")
    )
    for item in recursos.iterator():
        old_name = item.archivo.name
        old_path = safe_join(source_root, old_name)
        if not os.path.isfile(old_path):
            continue
        materia_id = item.clase.materia_curso.materia_id
        folder = "academico/clase_recursos" if reverse else f"academico/bolsa_recursos/materia_{materia_id}"
        target_name = f"{folder}/{uuid.uuid4().hex}_{old_name.rsplit('/', 1)[-1]}"
        with open(old_path, "rb") as source:
            saved_name = target_storage.save(target_name, File(source), max_length=100 if reverse else 255)
        ClaseRecurso.objects.using(schema_editor.connection.alias).filter(pk=item.pk).update(archivo=saved_name)
        pending_delete.add(old_path)

    if pending_delete:
        def delete_old_files():
            for path in pending_delete:
                try:
                    os.remove(path)
                except FileNotFoundError:
                    pass

        transaction.on_commit(delete_old_files, using=schema_editor.connection.alias)


def move_files_to_private(apps, schema_editor):
    move_resource_files(apps, schema_editor)


def move_files_to_public(apps, schema_editor):
    move_resource_files(apps, schema_editor, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0048_periodo_close_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claserecurso',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, null=True, storage=apps.academico.storage.BolsaRecursosStorage(), upload_to=apps.academico.models.clase_recurso_upload_path),
        ),
        migrations.RunPython(move_files_to_private, move_files_to_public),
    ]
