# Generated by Django 5.2.17 on 2026-09-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0049_alter_claserecurso_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'ordering': ['nombre'], 'permissions': [('access_bolsa_recursos', 'Puede acceder a la bolsa de recursos')]},
        ),
    ]
