# Generated by Django 5.2.17 on 2026-09-16 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0050_alter_recurso_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleCalificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveBigIntegerField()),
                ('nombre', models.CharField(max_length=500)),
                ('tipo', models.CharField(max_length=30)),
                ('modulo', models.CharField(blank=True, max_length=100)),
                ('instancia_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modulo_curso_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('categoria_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('nota_minima', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('nota_maxima', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('nota_formateada', models.CharField(blank=True, max_length=100)),
                ('rango_formateado', models.CharField(blank=True, max_length=100)),
                ('porcentaje_formateado', models.CharField(blank=True, max_length=100)),
                ('retroalimentacion', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('oculta', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('sincronizada_en', models.DateTimeField(auto_now=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.moodlematricula')),
            ],
            options={
                'db_table': '"academico"."moodle_calificacion"',
                'ordering': ['matricula__curso__materia_curso__materia__nombre', 'tipo', 'nombre', 'item_id'],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('matricula', 'item_id'), name='moodle_calificacion_matricula_item')],
            },
        ),
    ]
