# Generated by Django 5.2.17 on 2026-09-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0051_moodle_calificaciones"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moodlecalificacion",
            options={
                "default_permissions": (),
                "ordering": [
                    "matricula__curso__materia_curso__materia__nombre",
                    "tipo",
                    "nombre",
                    "item_id",
                ],
                "permissions": (
                    (
                        "access_docente_calificaciones",
                        "Puede acceder a las calificaciones docentes",
                    ),
                ),
            },
        ),
    ]
