# Generated by Django 5.2.17 on 2026-09-24

import django.db.models.deletion
from django.db import migrations, models


def preserve_existing_strategy_order(apps, schema_editor):
    Clase = apps.get_model("academico", "Clase")
    ClaseEstrategiaOrden = apps.get_model("academico", "ClaseEstrategiaOrden")
    through = Clase.estrategias.through
    database = schema_editor.connection.alias
    rows = (
        through.objects.using(database)
        .select_related("estrategia")
        .order_by("clase_id", "estrategia__nombre", "estrategia_id")
    )
    current_class_id = None
    order = 0
    pending = []
    for row in rows.iterator():
        if row.clase_id != current_class_id:
            current_class_id = row.clase_id
            order = 0
        order += 1
        pending.append(
            ClaseEstrategiaOrden(
                clase_id=row.clase_id,
                estrategia_id=row.estrategia_id,
                orden=order,
            )
        )
    ClaseEstrategiaOrden.objects.using(database).bulk_create(pending, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0057_group_transfer_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaseEstrategiaOrden",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "clase",
                    models.ForeignKey(
                        db_column="id_clase",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clase_estrategias_orden",
                        to="academico.clase",
                    ),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        db_column="id_estrategia",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clase_estrategias_orden",
                        to="academico.estrategia",
                    ),
                ),
            ],
            options={
                "db_table": '"academico"."clase_estrategia_orden"',
                "ordering": ["clase", "orden", "pk"],
                "unique_together": {("clase", "estrategia")},
            },
        ),
        migrations.RunPython(
            preserve_existing_strategy_order,
            migrations.RunPython.noop,
        ),
    ]
