# Generated by Django 5.2.17 on 2026-08-20 05:02

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        HStoreExtension(),
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS core;"),
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS matricula;"),
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS academico;"),
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS cartera;"),
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS auditoria;"),
        migrations.CreateModel(
            name='OperadorMovil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"core"."operador_movil"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"core"."tipo_identificacion"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, default='', max_length=13)),
                ('razon_social', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.TextField(blank=True, default='')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=80, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empresas_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"core"."empresa"',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_aux', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.TextField()),
                ('identificacion', models.CharField(default='', max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_celular', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('tipo', models.CharField(blank=True, max_length=2, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('es_cliente', models.BooleanField(default=True)),
                ('es_estudiante', models.BooleanField(default=False)),
                ('es_representante', models.BooleanField(default=False)),
                ('es_docente', models.BooleanField(default=False)),
                ('ingresar_portal', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('operador_movil', models.ForeignKey(blank=True, db_column='id_operador_movil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.operadormovil')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partners_actualizados', to=settings.AUTH_USER_MODEL)),
                ('tipo_identificacion', models.ForeignKey(db_column='id_tipo_identificacion', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipoidentificacion')),
            ],
            options={
                'db_table': '"core"."partner"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(max_length=50)),
                ('principal', models.BooleanField(default=False)),
                ('contacto_emergencia', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('partner_a', models.ForeignKey(db_column='id_partner_a', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relaciones_a', to='core.partner')),
                ('partner_b', models.ForeignKey(db_column='id_partner_b', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relaciones_b', to='core.partner')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_relaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"core"."partner_partner"',
                'unique_together': {('partner_a', 'partner_b', 'relacion')},
            },
        ),
    ]
