# Generated by Django 5.2.17 on 2026-08-22 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vistas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='usuario',
            field=models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
