# Generated by Django 5.2.17 on 2026-09-01 00:10

from django.db import migrations


def create_default_tipos_documento(apps, schema_editor):
    TipoIdentificacion = apps.get_model("core", "TipoIdentificacion")
    for nombre, codigo in (
        ("Cedula", "05"),
        ("RUC", "04"),
        ("Pasaporte", "06"),
    ):
        tipo, created = TipoIdentificacion.objects.get_or_create(
            nombre=nombre,
            defaults={"codigo": codigo, "activo": True},
        )
        if not created:
            update_fields = []
            if tipo.codigo != codigo:
                tipo.codigo = codigo
                update_fields.append("codigo")
            if not tipo.activo:
                tipo.activo = True
                update_fields.append("activo")
            if update_fields:
                tipo.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_partner_foto"),
    ]

    operations = [
        migrations.RunPython(create_default_tipos_documento, migrations.RunPython.noop),
    ]
