# Generated by Django 5.2.17 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_partner_full_name_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="logo",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="core/empresa/",
            ),
        ),
    ]
