# Generated by Django 5.2.17 on 2026-09-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_empresa_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={
                "db_table": '"core"."partner"',
                "ordering": ["nombre"],
                "permissions": (("deactivate_student", "Puede desactivar estudiantes"),),
            },
        ),
    ]
