# Generated by Django 5.2.17 on 2026-08-20 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('matricula', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_pago_debito', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_recibo_factura_deposito', models.CharField(blank=True, max_length=60, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('critica', 'Critica')], default='normal', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuotas_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"cartera"."cuota"',
                'ordering': ['fecha_pago_debito', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('es_venta', models.BooleanField(default=True)),
                ('es_pago', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='formas_pago_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"cartera"."forma_pago"',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('empresa', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_documento', models.CharField(blank=True, max_length=60, null=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='cartera/comprobantes/')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cuota', models.ForeignKey(db_column='id_cuota', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagos', to='cartera.cuota')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('forma_pago', models.ForeignKey(db_column='id_forma_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='cartera.formapago')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagos_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"cartera"."pago"',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_matricula', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('cerrado', 'Cerrado'), ('anulado', 'Anulado')], default='activo', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('ficha_inscripcion', models.OneToOneField(db_column='id_ficha_inscripcion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan_pago', to='matricula.fichainscripcion')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planes_pago_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"cartera"."plan_pago"',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='plan_pago',
            field=models.ForeignKey(db_column='id_plan_pago', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuotas', to='cartera.planpago'),
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('plan_pago', 'numero')},
        ),
    ]
