# Generated by Django 5.2.17 on 2026-08-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Atraso'), ('excused', 'Justificado')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['lesson_plan', 'student'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('evaluation_type', models.CharField(choices=[('process', 'Proceso'), ('final', 'Final'), ('simulator', 'Simulador')], default='process', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
            ],
            options={
                'ordering': ['-date', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('resource_type', models.CharField(choices=[('document', 'Documento'), ('video', 'Video'), ('link', 'Enlace'), ('slide', 'Diapositiva'), ('other', 'Otro')], default='document', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='academic/resources/')),
                ('is_ready', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('class_number', models.PositiveIntegerField(default=1)),
                ('planned_date', models.DateField(db_index=True)),
                ('objective', models.TextField()),
                ('activities', models.TextField()),
                ('expected_resources', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'En revision'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('completed', 'Completada')], db_index=True, default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['planned_date', 'classroom', 'class_number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('prompt', models.TextField()),
                ('answers', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Facil'), ('medium', 'Media'), ('hard', 'Dificil')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revision'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_index=True, default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['question_bank', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bank_type', models.CharField(choices=[('process', 'Proceso'), ('final', 'Simulador/final')], max_length=20)),
                ('target_questions', models.PositiveIntegerField(default=10)),
                ('reviewed_by_coordination', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['subject', 'topic', 'bank_type'],
            },
        ),
        migrations.CreateModel(
            name='StudentEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['evaluation', 'student'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('order', models.PositiveIntegerField(default=1)),
                ('objective', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['topic', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('archived', 'Archivado')], db_index=True, default='draft', max_length=20)),
            ],
            options={
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['academic_period', 'subject', 'teacher'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('order', models.PositiveIntegerField(default=1)),
                ('objective', models.TextField(blank=True)),
                ('class_count', models.PositiveIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('basic', 'Basica'), ('medium', 'Media'), ('advanced', 'Avanzada')], default='medium', max_length=20)),
                ('process_question_goal', models.PositiveIntegerField(default=10)),
                ('final_question_goal', models.PositiveIntegerField(default=10)),
            ],
            options={
                'ordering': ['syllabus', 'order', 'title'],
            },
        ),
    ]
