# Generated by Django 5.2.17 on 2026-08-20 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('institutions', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='people.student'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='institutions.classroom'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_lesson_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academic.lessonplan'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='lesson_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='academic.lessonplan'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.lessonplan'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_banks', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='academic.questionbank'),
        ),
        migrations.AddField(
            model_name='studentevaluationresult',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academic.evaluation'),
        ),
        migrations.AddField(
            model_name='studentevaluationresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_results', to='people.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_banks', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_banks', to='academic.subtopic'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='academic.subtopic'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='syllabuses', to='institutions.academicperiod'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabuses', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabuses', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='institutions.academicperiod'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='institutions.classroom'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academic.syllabus'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='academic.topic'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_banks', to='academic.topic'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='academic.topic'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='academic.topic'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('lesson_plan', 'student'), name='uniq_attendance_by_lesson_student'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_by', 'status'], name='academic_qu_created_9399fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentevaluationresult',
            constraint=models.UniqueConstraint(fields=('evaluation', 'student'), name='uniq_result_by_evaluation_student'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('institution', 'code'), name='uniq_active_subject_code_by_institution'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['teacher', 'academic_period', 'is_active'], name='academic_te_teacher_8c4ff6_idx'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('syllabus', 'order'), name='uniq_active_topic_order_by_syllabus'),
        ),
        migrations.AddConstraint(
            model_name='subtopic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('topic', 'order'), name='uniq_active_subtopic_order_by_topic'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['institution', 'bank_type'], name='academic_qu_institu_b112eb_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['subject', 'topic', 'subtopic'], name='academic_qu_subject_fe3e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['teacher', 'status'], name='academic_le_teacher_0d5854_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['institution', 'planned_date'], name='academic_le_institu_1d5610_idx'),
        ),
    ]
