# Generated by Django 5.2.17 on 2026-08-20 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('login', 'Ingreso'), ('export', 'Exportar'), ('approve', 'Aprobar'), ('reject', 'Rechazar')], db_index=True, max_length=20)),
                ('model_name', models.CharField(db_index=True, max_length=120)),
                ('object_pk', models.CharField(blank=True, max_length=80)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='institutions.institution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'action'], name='audit_audit_institu_437f4f_idx'), models.Index(fields=['model_name', 'object_pk'], name='audit_audit_model_n_be445d_idx')],
            },
        ),
    ]
