# Generated by Django 5.2.17 on 2026-08-20 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('seccion', models.CharField(blank=True, max_length=40, null=True)),
                ('jornada', models.CharField(blank=True, max_length=40, null=True)),
                ('horario', models.CharField(blank=True, max_length=120, null=True)),
                ('hora', models.CharField(blank=True, max_length=80, null=True)),
                ('duracion', models.CharField(blank=True, max_length=80, null=True)),
                ('capacidad', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aulas_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"matricula"."aula"',
                'ordering': ['periodo_academico', 'nombre', 'seccion'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('grado', models.CharField(blank=True, max_length=60, null=True)),
                ('carrera', models.CharField(blank=True, max_length=160, null=True)),
                ('universidad', models.CharField(blank=True, max_length=160, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursos_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"matricula"."curso"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FichaInscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('colegio', models.CharField(blank=True, max_length=200, null=True)),
                ('curso_grado', models.CharField(blank=True, max_length=120, null=True)),
                ('nota_grado', models.CharField(blank=True, max_length=60, null=True)),
                ('carrera', models.CharField(blank=True, max_length=160, null=True)),
                ('universidad', models.CharField(blank=True, max_length=160, null=True)),
                ('nombre_conyuge', models.CharField(blank=True, max_length=200, null=True)),
                ('ocupacion_conyuge', models.CharField(blank=True, max_length=120, null=True)),
                ('correo_estudiante', models.TextField(blank=True, null=True)),
                ('correo_representante', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=120, null=True)),
                ('hora', models.CharField(blank=True, max_length=80, null=True)),
                ('duracion', models.CharField(blank=True, max_length=80, null=True)),
                ('forma_pago_convenio', models.CharField(blank=True, choices=[('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('unico', 'Un solo pago total')], max_length=20, null=True)),
                ('fecha_proximo_pago', models.DateField(blank=True, null=True)),
                ('valor_proximo_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total_curso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_matricula', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promo', models.BooleanField(default=False)),
                ('autorizacion_imagen', models.BooleanField(default=False)),
                ('acepta_garantia', models.BooleanField(default=False)),
                ('acepta_no_devolucion', models.BooleanField(default=False)),
                ('firma_representante', models.TextField(blank=True, null=True)),
                ('ci_representante_firma', models.CharField(blank=True, max_length=20, null=True)),
                ('firma_director_asesor', models.TextField(blank=True, null=True)),
                ('ci_director_asesor', models.CharField(blank=True, max_length=20, null=True)),
                ('archivo_contrato', models.FileField(blank=True, null=True, upload_to='matricula/contratos/')),
                ('archivo_ficha_firmada', models.FileField(blank=True, null=True, upload_to='matricula/fichas/')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('retirada', 'Retirada'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(blank=True, db_column='id_aula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.aula')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fichas_cliente', to='core.partner')),
                ('curso', models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.curso')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fichas_estudiante', to='core.partner')),
                ('representante', models.ForeignKey(blank=True, db_column='id_representante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fichas_representante', to='core.partner')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fichas_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"matricula"."ficha_inscripcion"',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AulaHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('aula_destino', models.ForeignKey(db_column='id_aula_destino', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historial_destino', to='matricula.aula')),
                ('aula_origen', models.ForeignKey(blank=True, db_column='id_aula_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historial_origen', to='matricula.aula')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cambios_aula', to=settings.AUTH_USER_MODEL)),
                ('ficha_inscripcion', models.ForeignKey(db_column='id_ficha_inscripcion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='aula_historial', to='matricula.fichainscripcion')),
            ],
            options={
                'db_table': '"matricula"."aula_historial"',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('regimen', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='borrador', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empresa')),
                ('usuario_updated', models.ForeignKey(blank=True, db_column='id_usuario_updated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='periodos_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"matricula"."periodo_academico"',
                'ordering': ['-fecha_inicio', 'nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='fichainscripcion',
            name='periodo_academico',
            field=models.ForeignKey(db_column='id_periodo_academico', on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.periodoacademico'),
        ),
        migrations.AddField(
            model_name='aula',
            name='periodo_academico',
            field=models.ForeignKey(db_column='id_periodo_academico', on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.periodoacademico'),
        ),
        migrations.AlterUniqueTogether(
            name='fichainscripcion',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('periodo_academico', 'nombre', 'seccion')},
        ),
    ]
